
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the browser.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/index-browser"

export type * from '../models.js'
export type * from './prismaNamespace.js'

export const Decimal = runtime.Decimal


export const NullTypes = {
  DbNull: runtime.objectEnumValues.classes.DbNull as (new (secret: never) => typeof runtime.objectEnumValues.instances.DbNull),
  JsonNull: runtime.objectEnumValues.classes.JsonNull as (new (secret: never) => typeof runtime.objectEnumValues.instances.JsonNull),
  AnyNull: runtime.objectEnumValues.classes.AnyNull as (new (secret: never) => typeof runtime.objectEnumValues.instances.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.objectEnumValues.instances.DbNull
/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.objectEnumValues.instances.JsonNull
/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.objectEnumValues.instances.AnyNull


export const ModelName = {
  User: 'User',
  Profile: 'Profile',
  Category: 'Category',
  Gig: 'Gig',
  Order: 'Order',
  Conversation: 'Conversation',
  Message: 'Message',
  Review: 'Review',
  Wallet: 'Wallet',
  Transaction: 'Transaction',
  Notification: 'Notification',
  AdminLog: 'AdminLog',
  Setting: 'Setting',
  Dispute: 'Dispute'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]

/*
 * Enums
 */

export const TransactionIsolationLevel = runtime.makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
} as const)

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const UserScalarFieldEnum = {
  id: 'id',
  full_name: 'full_name',
  username: 'username',
  email: 'email',
  password: 'password',
  role: 'role',
  avatar_url: 'avatar_url',
  bio: 'bio',
  country: 'country',
  verified: 'verified',
  created_at: 'created_at',
  updated_at: 'updated_at'
} as const

export type UserScalarFieldEnum = (typeof UserScalarFieldEnum)[keyof typeof UserScalarFieldEnum]


export const ProfileScalarFieldEnum = {
  id: 'id',
  user_id: 'user_id',
  title: 'title',
  hourly_rate: 'hourly_rate',
  skills: 'skills',
  experience_years: 'experience_years',
  languages: 'languages',
  portfolio_url: 'portfolio_url',
  availability: 'availability',
  rating_avg: 'rating_avg',
  total_reviews: 'total_reviews'
} as const

export type ProfileScalarFieldEnum = (typeof ProfileScalarFieldEnum)[keyof typeof ProfileScalarFieldEnum]


export const CategoryScalarFieldEnum = {
  id: 'id',
  name: 'name',
  description: 'description',
  parent_id: 'parent_id',
  icon: 'icon'
} as const

export type CategoryScalarFieldEnum = (typeof CategoryScalarFieldEnum)[keyof typeof CategoryScalarFieldEnum]


export const GigScalarFieldEnum = {
  id: 'id',
  user_id: 'user_id',
  title: 'title',
  description: 'description',
  category_id: 'category_id',
  price_basic: 'price_basic',
  price_standard: 'price_standard',
  price_premium: 'price_premium',
  delivery_days: 'delivery_days',
  revisions: 'revisions',
  thumbnail: 'thumbnail',
  images: 'images',
  status: 'status',
  created_at: 'created_at'
} as const

export type GigScalarFieldEnum = (typeof GigScalarFieldEnum)[keyof typeof GigScalarFieldEnum]


export const OrderScalarFieldEnum = {
  id: 'id',
  buyer_id: 'buyer_id',
  seller_id: 'seller_id',
  gig_id: 'gig_id',
  status: 'status',
  amount: 'amount',
  delivery_date: 'delivery_date',
  created_at: 'created_at',
  updated_at: 'updated_at'
} as const

export type OrderScalarFieldEnum = (typeof OrderScalarFieldEnum)[keyof typeof OrderScalarFieldEnum]


export const ConversationScalarFieldEnum = {
  id: 'id',
  buyer_id: 'buyer_id',
  seller_id: 'seller_id',
  last_message: 'last_message',
  updated_at: 'updated_at'
} as const

export type ConversationScalarFieldEnum = (typeof ConversationScalarFieldEnum)[keyof typeof ConversationScalarFieldEnum]


export const MessageScalarFieldEnum = {
  id: 'id',
  conversation_id: 'conversation_id',
  sender_id: 'sender_id',
  content: 'content',
  attachments: 'attachments',
  is_read: 'is_read',
  sent_at: 'sent_at'
} as const

export type MessageScalarFieldEnum = (typeof MessageScalarFieldEnum)[keyof typeof MessageScalarFieldEnum]


export const ReviewScalarFieldEnum = {
  id: 'id',
  order_id: 'order_id',
  reviewer_id: 'reviewer_id',
  reviewee_id: 'reviewee_id',
  rating: 'rating',
  comment: 'comment',
  created_at: 'created_at'
} as const

export type ReviewScalarFieldEnum = (typeof ReviewScalarFieldEnum)[keyof typeof ReviewScalarFieldEnum]


export const WalletScalarFieldEnum = {
  id: 'id',
  user_id: 'user_id',
  balance: 'balance',
  currency: 'currency',
  last_updated: 'last_updated'
} as const

export type WalletScalarFieldEnum = (typeof WalletScalarFieldEnum)[keyof typeof WalletScalarFieldEnum]


export const TransactionScalarFieldEnum = {
  id: 'id',
  wallet_id: 'wallet_id',
  type: 'type',
  amount: 'amount',
  reference: 'reference',
  created_at: 'created_at'
} as const

export type TransactionScalarFieldEnum = (typeof TransactionScalarFieldEnum)[keyof typeof TransactionScalarFieldEnum]


export const NotificationScalarFieldEnum = {
  id: 'id',
  user_id: 'user_id',
  title: 'title',
  message: 'message',
  type: 'type',
  is_read: 'is_read',
  created_at: 'created_at'
} as const

export type NotificationScalarFieldEnum = (typeof NotificationScalarFieldEnum)[keyof typeof NotificationScalarFieldEnum]


export const AdminLogScalarFieldEnum = {
  id: 'id',
  admin_id: 'admin_id',
  action: 'action',
  target_id: 'target_id',
  target_type: 'target_type',
  created_at: 'created_at'
} as const

export type AdminLogScalarFieldEnum = (typeof AdminLogScalarFieldEnum)[keyof typeof AdminLogScalarFieldEnum]


export const SettingScalarFieldEnum = {
  id: 'id',
  key: 'key',
  value: 'value',
  updated_at: 'updated_at'
} as const

export type SettingScalarFieldEnum = (typeof SettingScalarFieldEnum)[keyof typeof SettingScalarFieldEnum]


export const DisputeScalarFieldEnum = {
  id: 'id',
  order_id: 'order_id',
  raised_by: 'raised_by',
  reason: 'reason',
  evidence: 'evidence',
  status: 'status',
  resolution: 'resolution',
  created_at: 'created_at',
  resolved_at: 'resolved_at'
} as const

export type DisputeScalarFieldEnum = (typeof DisputeScalarFieldEnum)[keyof typeof DisputeScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
} as const

export type QueryMode = (typeof QueryMode)[keyof typeof QueryMode]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]

