
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// @ts-nocheck 
/*
 * This file exports the `Gig` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model Gig
 * 
 */
export type GigModel = runtime.Types.Result.DefaultSelection<Prisma.$GigPayload>

export type AggregateGig = {
  _count: GigCountAggregateOutputType | null
  _avg: GigAvgAggregateOutputType | null
  _sum: GigSumAggregateOutputType | null
  _min: GigMinAggregateOutputType | null
  _max: GigMaxAggregateOutputType | null
}

export type GigAvgAggregateOutputType = {
  price_basic: runtime.Decimal | null
  price_standard: runtime.Decimal | null
  price_premium: runtime.Decimal | null
  delivery_days: number | null
  revisions: number | null
}

export type GigSumAggregateOutputType = {
  price_basic: runtime.Decimal | null
  price_standard: runtime.Decimal | null
  price_premium: runtime.Decimal | null
  delivery_days: number | null
  revisions: number | null
}

export type GigMinAggregateOutputType = {
  id: string | null
  user_id: string | null
  title: string | null
  description: string | null
  category_id: string | null
  price_basic: runtime.Decimal | null
  price_standard: runtime.Decimal | null
  price_premium: runtime.Decimal | null
  delivery_days: number | null
  revisions: number | null
  thumbnail: string | null
  images: string | null
  status: string | null
  created_at: Date | null
}

export type GigMaxAggregateOutputType = {
  id: string | null
  user_id: string | null
  title: string | null
  description: string | null
  category_id: string | null
  price_basic: runtime.Decimal | null
  price_standard: runtime.Decimal | null
  price_premium: runtime.Decimal | null
  delivery_days: number | null
  revisions: number | null
  thumbnail: string | null
  images: string | null
  status: string | null
  created_at: Date | null
}

export type GigCountAggregateOutputType = {
  id: number
  user_id: number
  title: number
  description: number
  category_id: number
  price_basic: number
  price_standard: number
  price_premium: number
  delivery_days: number
  revisions: number
  thumbnail: number
  images: number
  status: number
  created_at: number
  _all: number
}


export type GigAvgAggregateInputType = {
  price_basic?: true
  price_standard?: true
  price_premium?: true
  delivery_days?: true
  revisions?: true
}

export type GigSumAggregateInputType = {
  price_basic?: true
  price_standard?: true
  price_premium?: true
  delivery_days?: true
  revisions?: true
}

export type GigMinAggregateInputType = {
  id?: true
  user_id?: true
  title?: true
  description?: true
  category_id?: true
  price_basic?: true
  price_standard?: true
  price_premium?: true
  delivery_days?: true
  revisions?: true
  thumbnail?: true
  images?: true
  status?: true
  created_at?: true
}

export type GigMaxAggregateInputType = {
  id?: true
  user_id?: true
  title?: true
  description?: true
  category_id?: true
  price_basic?: true
  price_standard?: true
  price_premium?: true
  delivery_days?: true
  revisions?: true
  thumbnail?: true
  images?: true
  status?: true
  created_at?: true
}

export type GigCountAggregateInputType = {
  id?: true
  user_id?: true
  title?: true
  description?: true
  category_id?: true
  price_basic?: true
  price_standard?: true
  price_premium?: true
  delivery_days?: true
  revisions?: true
  thumbnail?: true
  images?: true
  status?: true
  created_at?: true
  _all?: true
}

export type GigAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Gig to aggregate.
   */
  where?: Prisma.GigWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Gigs to fetch.
   */
  orderBy?: Prisma.GigOrderByWithRelationInput | Prisma.GigOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.GigWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Gigs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Gigs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Gigs
  **/
  _count?: true | GigCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: GigAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: GigSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: GigMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: GigMaxAggregateInputType
}

export type GetGigAggregateType<T extends GigAggregateArgs> = {
      [P in keyof T & keyof AggregateGig]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateGig[P]>
    : Prisma.GetScalarType<T[P], AggregateGig[P]>
}




export type GigGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.GigWhereInput
  orderBy?: Prisma.GigOrderByWithAggregationInput | Prisma.GigOrderByWithAggregationInput[]
  by: Prisma.GigScalarFieldEnum[] | Prisma.GigScalarFieldEnum
  having?: Prisma.GigScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: GigCountAggregateInputType | true
  _avg?: GigAvgAggregateInputType
  _sum?: GigSumAggregateInputType
  _min?: GigMinAggregateInputType
  _max?: GigMaxAggregateInputType
}

export type GigGroupByOutputType = {
  id: string
  user_id: string
  title: string
  description: string
  category_id: string
  price_basic: runtime.Decimal
  price_standard: runtime.Decimal
  price_premium: runtime.Decimal
  delivery_days: number
  revisions: number
  thumbnail: string | null
  images: string | null
  status: string
  created_at: Date
  _count: GigCountAggregateOutputType | null
  _avg: GigAvgAggregateOutputType | null
  _sum: GigSumAggregateOutputType | null
  _min: GigMinAggregateOutputType | null
  _max: GigMaxAggregateOutputType | null
}

type GetGigGroupByPayload<T extends GigGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<GigGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof GigGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], GigGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], GigGroupByOutputType[P]>
      }
    >
  >



export type GigWhereInput = {
  AND?: Prisma.GigWhereInput | Prisma.GigWhereInput[]
  OR?: Prisma.GigWhereInput[]
  NOT?: Prisma.GigWhereInput | Prisma.GigWhereInput[]
  id?: Prisma.StringFilter<"Gig"> | string
  user_id?: Prisma.StringFilter<"Gig"> | string
  title?: Prisma.StringFilter<"Gig"> | string
  description?: Prisma.StringFilter<"Gig"> | string
  category_id?: Prisma.StringFilter<"Gig"> | string
  price_basic?: Prisma.DecimalFilter<"Gig"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  price_standard?: Prisma.DecimalFilter<"Gig"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  price_premium?: Prisma.DecimalFilter<"Gig"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  delivery_days?: Prisma.IntFilter<"Gig"> | number
  revisions?: Prisma.IntFilter<"Gig"> | number
  thumbnail?: Prisma.StringNullableFilter<"Gig"> | string | null
  images?: Prisma.StringNullableFilter<"Gig"> | string | null
  status?: Prisma.StringFilter<"Gig"> | string
  created_at?: Prisma.DateTimeFilter<"Gig"> | Date | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  category?: Prisma.XOR<Prisma.CategoryScalarRelationFilter, Prisma.CategoryWhereInput>
  orders?: Prisma.OrderListRelationFilter
}

export type GigOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  user_id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrder
  category_id?: Prisma.SortOrder
  price_basic?: Prisma.SortOrder
  price_standard?: Prisma.SortOrder
  price_premium?: Prisma.SortOrder
  delivery_days?: Prisma.SortOrder
  revisions?: Prisma.SortOrder
  thumbnail?: Prisma.SortOrderInput | Prisma.SortOrder
  images?: Prisma.SortOrderInput | Prisma.SortOrder
  status?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  user?: Prisma.UserOrderByWithRelationInput
  category?: Prisma.CategoryOrderByWithRelationInput
  orders?: Prisma.OrderOrderByRelationAggregateInput
}

export type GigWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.GigWhereInput | Prisma.GigWhereInput[]
  OR?: Prisma.GigWhereInput[]
  NOT?: Prisma.GigWhereInput | Prisma.GigWhereInput[]
  user_id?: Prisma.StringFilter<"Gig"> | string
  title?: Prisma.StringFilter<"Gig"> | string
  description?: Prisma.StringFilter<"Gig"> | string
  category_id?: Prisma.StringFilter<"Gig"> | string
  price_basic?: Prisma.DecimalFilter<"Gig"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  price_standard?: Prisma.DecimalFilter<"Gig"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  price_premium?: Prisma.DecimalFilter<"Gig"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  delivery_days?: Prisma.IntFilter<"Gig"> | number
  revisions?: Prisma.IntFilter<"Gig"> | number
  thumbnail?: Prisma.StringNullableFilter<"Gig"> | string | null
  images?: Prisma.StringNullableFilter<"Gig"> | string | null
  status?: Prisma.StringFilter<"Gig"> | string
  created_at?: Prisma.DateTimeFilter<"Gig"> | Date | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  category?: Prisma.XOR<Prisma.CategoryScalarRelationFilter, Prisma.CategoryWhereInput>
  orders?: Prisma.OrderListRelationFilter
}, "id">

export type GigOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  user_id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrder
  category_id?: Prisma.SortOrder
  price_basic?: Prisma.SortOrder
  price_standard?: Prisma.SortOrder
  price_premium?: Prisma.SortOrder
  delivery_days?: Prisma.SortOrder
  revisions?: Prisma.SortOrder
  thumbnail?: Prisma.SortOrderInput | Prisma.SortOrder
  images?: Prisma.SortOrderInput | Prisma.SortOrder
  status?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  _count?: Prisma.GigCountOrderByAggregateInput
  _avg?: Prisma.GigAvgOrderByAggregateInput
  _max?: Prisma.GigMaxOrderByAggregateInput
  _min?: Prisma.GigMinOrderByAggregateInput
  _sum?: Prisma.GigSumOrderByAggregateInput
}

export type GigScalarWhereWithAggregatesInput = {
  AND?: Prisma.GigScalarWhereWithAggregatesInput | Prisma.GigScalarWhereWithAggregatesInput[]
  OR?: Prisma.GigScalarWhereWithAggregatesInput[]
  NOT?: Prisma.GigScalarWhereWithAggregatesInput | Prisma.GigScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Gig"> | string
  user_id?: Prisma.StringWithAggregatesFilter<"Gig"> | string
  title?: Prisma.StringWithAggregatesFilter<"Gig"> | string
  description?: Prisma.StringWithAggregatesFilter<"Gig"> | string
  category_id?: Prisma.StringWithAggregatesFilter<"Gig"> | string
  price_basic?: Prisma.DecimalWithAggregatesFilter<"Gig"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  price_standard?: Prisma.DecimalWithAggregatesFilter<"Gig"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  price_premium?: Prisma.DecimalWithAggregatesFilter<"Gig"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  delivery_days?: Prisma.IntWithAggregatesFilter<"Gig"> | number
  revisions?: Prisma.IntWithAggregatesFilter<"Gig"> | number
  thumbnail?: Prisma.StringNullableWithAggregatesFilter<"Gig"> | string | null
  images?: Prisma.StringNullableWithAggregatesFilter<"Gig"> | string | null
  status?: Prisma.StringWithAggregatesFilter<"Gig"> | string
  created_at?: Prisma.DateTimeWithAggregatesFilter<"Gig"> | Date | string
}

export type GigCreateInput = {
  id?: string
  title: string
  description: string
  price_basic: runtime.Decimal | runtime.DecimalJsLike | number | string
  price_standard: runtime.Decimal | runtime.DecimalJsLike | number | string
  price_premium: runtime.Decimal | runtime.DecimalJsLike | number | string
  delivery_days: number
  revisions: number
  thumbnail?: string | null
  images?: string | null
  status?: string
  created_at?: Date | string
  user: Prisma.UserCreateNestedOneWithoutGigsInput
  category: Prisma.CategoryCreateNestedOneWithoutGigsInput
  orders?: Prisma.OrderCreateNestedManyWithoutGigInput
}

export type GigUncheckedCreateInput = {
  id?: string
  user_id: string
  title: string
  description: string
  category_id: string
  price_basic: runtime.Decimal | runtime.DecimalJsLike | number | string
  price_standard: runtime.Decimal | runtime.DecimalJsLike | number | string
  price_premium: runtime.Decimal | runtime.DecimalJsLike | number | string
  delivery_days: number
  revisions: number
  thumbnail?: string | null
  images?: string | null
  status?: string
  created_at?: Date | string
  orders?: Prisma.OrderUncheckedCreateNestedManyWithoutGigInput
}

export type GigUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  price_basic?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  price_standard?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  price_premium?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  delivery_days?: Prisma.IntFieldUpdateOperationsInput | number
  revisions?: Prisma.IntFieldUpdateOperationsInput | number
  thumbnail?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  images?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutGigsNestedInput
  category?: Prisma.CategoryUpdateOneRequiredWithoutGigsNestedInput
  orders?: Prisma.OrderUpdateManyWithoutGigNestedInput
}

export type GigUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  user_id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  category_id?: Prisma.StringFieldUpdateOperationsInput | string
  price_basic?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  price_standard?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  price_premium?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  delivery_days?: Prisma.IntFieldUpdateOperationsInput | number
  revisions?: Prisma.IntFieldUpdateOperationsInput | number
  thumbnail?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  images?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  orders?: Prisma.OrderUncheckedUpdateManyWithoutGigNestedInput
}

export type GigCreateManyInput = {
  id?: string
  user_id: string
  title: string
  description: string
  category_id: string
  price_basic: runtime.Decimal | runtime.DecimalJsLike | number | string
  price_standard: runtime.Decimal | runtime.DecimalJsLike | number | string
  price_premium: runtime.Decimal | runtime.DecimalJsLike | number | string
  delivery_days: number
  revisions: number
  thumbnail?: string | null
  images?: string | null
  status?: string
  created_at?: Date | string
}

export type GigUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  price_basic?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  price_standard?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  price_premium?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  delivery_days?: Prisma.IntFieldUpdateOperationsInput | number
  revisions?: Prisma.IntFieldUpdateOperationsInput | number
  thumbnail?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  images?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type GigUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  user_id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  category_id?: Prisma.StringFieldUpdateOperationsInput | string
  price_basic?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  price_standard?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  price_premium?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  delivery_days?: Prisma.IntFieldUpdateOperationsInput | number
  revisions?: Prisma.IntFieldUpdateOperationsInput | number
  thumbnail?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  images?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type GigListRelationFilter = {
  every?: Prisma.GigWhereInput
  some?: Prisma.GigWhereInput
  none?: Prisma.GigWhereInput
}

export type GigOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type GigCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  user_id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrder
  category_id?: Prisma.SortOrder
  price_basic?: Prisma.SortOrder
  price_standard?: Prisma.SortOrder
  price_premium?: Prisma.SortOrder
  delivery_days?: Prisma.SortOrder
  revisions?: Prisma.SortOrder
  thumbnail?: Prisma.SortOrder
  images?: Prisma.SortOrder
  status?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
}

export type GigAvgOrderByAggregateInput = {
  price_basic?: Prisma.SortOrder
  price_standard?: Prisma.SortOrder
  price_premium?: Prisma.SortOrder
  delivery_days?: Prisma.SortOrder
  revisions?: Prisma.SortOrder
}

export type GigMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  user_id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrder
  category_id?: Prisma.SortOrder
  price_basic?: Prisma.SortOrder
  price_standard?: Prisma.SortOrder
  price_premium?: Prisma.SortOrder
  delivery_days?: Prisma.SortOrder
  revisions?: Prisma.SortOrder
  thumbnail?: Prisma.SortOrder
  images?: Prisma.SortOrder
  status?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
}

export type GigMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  user_id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrder
  category_id?: Prisma.SortOrder
  price_basic?: Prisma.SortOrder
  price_standard?: Prisma.SortOrder
  price_premium?: Prisma.SortOrder
  delivery_days?: Prisma.SortOrder
  revisions?: Prisma.SortOrder
  thumbnail?: Prisma.SortOrder
  images?: Prisma.SortOrder
  status?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
}

export type GigSumOrderByAggregateInput = {
  price_basic?: Prisma.SortOrder
  price_standard?: Prisma.SortOrder
  price_premium?: Prisma.SortOrder
  delivery_days?: Prisma.SortOrder
  revisions?: Prisma.SortOrder
}

export type GigScalarRelationFilter = {
  is?: Prisma.GigWhereInput
  isNot?: Prisma.GigWhereInput
}

export type GigCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.GigCreateWithoutUserInput, Prisma.GigUncheckedCreateWithoutUserInput> | Prisma.GigCreateWithoutUserInput[] | Prisma.GigUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.GigCreateOrConnectWithoutUserInput | Prisma.GigCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.GigCreateManyUserInputEnvelope
  connect?: Prisma.GigWhereUniqueInput | Prisma.GigWhereUniqueInput[]
}

export type GigUncheckedCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.GigCreateWithoutUserInput, Prisma.GigUncheckedCreateWithoutUserInput> | Prisma.GigCreateWithoutUserInput[] | Prisma.GigUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.GigCreateOrConnectWithoutUserInput | Prisma.GigCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.GigCreateManyUserInputEnvelope
  connect?: Prisma.GigWhereUniqueInput | Prisma.GigWhereUniqueInput[]
}

export type GigUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.GigCreateWithoutUserInput, Prisma.GigUncheckedCreateWithoutUserInput> | Prisma.GigCreateWithoutUserInput[] | Prisma.GigUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.GigCreateOrConnectWithoutUserInput | Prisma.GigCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.GigUpsertWithWhereUniqueWithoutUserInput | Prisma.GigUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.GigCreateManyUserInputEnvelope
  set?: Prisma.GigWhereUniqueInput | Prisma.GigWhereUniqueInput[]
  disconnect?: Prisma.GigWhereUniqueInput | Prisma.GigWhereUniqueInput[]
  delete?: Prisma.GigWhereUniqueInput | Prisma.GigWhereUniqueInput[]
  connect?: Prisma.GigWhereUniqueInput | Prisma.GigWhereUniqueInput[]
  update?: Prisma.GigUpdateWithWhereUniqueWithoutUserInput | Prisma.GigUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.GigUpdateManyWithWhereWithoutUserInput | Prisma.GigUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.GigScalarWhereInput | Prisma.GigScalarWhereInput[]
}

export type GigUncheckedUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.GigCreateWithoutUserInput, Prisma.GigUncheckedCreateWithoutUserInput> | Prisma.GigCreateWithoutUserInput[] | Prisma.GigUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.GigCreateOrConnectWithoutUserInput | Prisma.GigCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.GigUpsertWithWhereUniqueWithoutUserInput | Prisma.GigUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.GigCreateManyUserInputEnvelope
  set?: Prisma.GigWhereUniqueInput | Prisma.GigWhereUniqueInput[]
  disconnect?: Prisma.GigWhereUniqueInput | Prisma.GigWhereUniqueInput[]
  delete?: Prisma.GigWhereUniqueInput | Prisma.GigWhereUniqueInput[]
  connect?: Prisma.GigWhereUniqueInput | Prisma.GigWhereUniqueInput[]
  update?: Prisma.GigUpdateWithWhereUniqueWithoutUserInput | Prisma.GigUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.GigUpdateManyWithWhereWithoutUserInput | Prisma.GigUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.GigScalarWhereInput | Prisma.GigScalarWhereInput[]
}

export type GigCreateNestedManyWithoutCategoryInput = {
  create?: Prisma.XOR<Prisma.GigCreateWithoutCategoryInput, Prisma.GigUncheckedCreateWithoutCategoryInput> | Prisma.GigCreateWithoutCategoryInput[] | Prisma.GigUncheckedCreateWithoutCategoryInput[]
  connectOrCreate?: Prisma.GigCreateOrConnectWithoutCategoryInput | Prisma.GigCreateOrConnectWithoutCategoryInput[]
  createMany?: Prisma.GigCreateManyCategoryInputEnvelope
  connect?: Prisma.GigWhereUniqueInput | Prisma.GigWhereUniqueInput[]
}

export type GigUncheckedCreateNestedManyWithoutCategoryInput = {
  create?: Prisma.XOR<Prisma.GigCreateWithoutCategoryInput, Prisma.GigUncheckedCreateWithoutCategoryInput> | Prisma.GigCreateWithoutCategoryInput[] | Prisma.GigUncheckedCreateWithoutCategoryInput[]
  connectOrCreate?: Prisma.GigCreateOrConnectWithoutCategoryInput | Prisma.GigCreateOrConnectWithoutCategoryInput[]
  createMany?: Prisma.GigCreateManyCategoryInputEnvelope
  connect?: Prisma.GigWhereUniqueInput | Prisma.GigWhereUniqueInput[]
}

export type GigUpdateManyWithoutCategoryNestedInput = {
  create?: Prisma.XOR<Prisma.GigCreateWithoutCategoryInput, Prisma.GigUncheckedCreateWithoutCategoryInput> | Prisma.GigCreateWithoutCategoryInput[] | Prisma.GigUncheckedCreateWithoutCategoryInput[]
  connectOrCreate?: Prisma.GigCreateOrConnectWithoutCategoryInput | Prisma.GigCreateOrConnectWithoutCategoryInput[]
  upsert?: Prisma.GigUpsertWithWhereUniqueWithoutCategoryInput | Prisma.GigUpsertWithWhereUniqueWithoutCategoryInput[]
  createMany?: Prisma.GigCreateManyCategoryInputEnvelope
  set?: Prisma.GigWhereUniqueInput | Prisma.GigWhereUniqueInput[]
  disconnect?: Prisma.GigWhereUniqueInput | Prisma.GigWhereUniqueInput[]
  delete?: Prisma.GigWhereUniqueInput | Prisma.GigWhereUniqueInput[]
  connect?: Prisma.GigWhereUniqueInput | Prisma.GigWhereUniqueInput[]
  update?: Prisma.GigUpdateWithWhereUniqueWithoutCategoryInput | Prisma.GigUpdateWithWhereUniqueWithoutCategoryInput[]
  updateMany?: Prisma.GigUpdateManyWithWhereWithoutCategoryInput | Prisma.GigUpdateManyWithWhereWithoutCategoryInput[]
  deleteMany?: Prisma.GigScalarWhereInput | Prisma.GigScalarWhereInput[]
}

export type GigUncheckedUpdateManyWithoutCategoryNestedInput = {
  create?: Prisma.XOR<Prisma.GigCreateWithoutCategoryInput, Prisma.GigUncheckedCreateWithoutCategoryInput> | Prisma.GigCreateWithoutCategoryInput[] | Prisma.GigUncheckedCreateWithoutCategoryInput[]
  connectOrCreate?: Prisma.GigCreateOrConnectWithoutCategoryInput | Prisma.GigCreateOrConnectWithoutCategoryInput[]
  upsert?: Prisma.GigUpsertWithWhereUniqueWithoutCategoryInput | Prisma.GigUpsertWithWhereUniqueWithoutCategoryInput[]
  createMany?: Prisma.GigCreateManyCategoryInputEnvelope
  set?: Prisma.GigWhereUniqueInput | Prisma.GigWhereUniqueInput[]
  disconnect?: Prisma.GigWhereUniqueInput | Prisma.GigWhereUniqueInput[]
  delete?: Prisma.GigWhereUniqueInput | Prisma.GigWhereUniqueInput[]
  connect?: Prisma.GigWhereUniqueInput | Prisma.GigWhereUniqueInput[]
  update?: Prisma.GigUpdateWithWhereUniqueWithoutCategoryInput | Prisma.GigUpdateWithWhereUniqueWithoutCategoryInput[]
  updateMany?: Prisma.GigUpdateManyWithWhereWithoutCategoryInput | Prisma.GigUpdateManyWithWhereWithoutCategoryInput[]
  deleteMany?: Prisma.GigScalarWhereInput | Prisma.GigScalarWhereInput[]
}

export type DecimalFieldUpdateOperationsInput = {
  set?: runtime.Decimal | runtime.DecimalJsLike | number | string
  increment?: runtime.Decimal | runtime.DecimalJsLike | number | string
  decrement?: runtime.Decimal | runtime.DecimalJsLike | number | string
  multiply?: runtime.Decimal | runtime.DecimalJsLike | number | string
  divide?: runtime.Decimal | runtime.DecimalJsLike | number | string
}

export type IntFieldUpdateOperationsInput = {
  set?: number
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type GigCreateNestedOneWithoutOrdersInput = {
  create?: Prisma.XOR<Prisma.GigCreateWithoutOrdersInput, Prisma.GigUncheckedCreateWithoutOrdersInput>
  connectOrCreate?: Prisma.GigCreateOrConnectWithoutOrdersInput
  connect?: Prisma.GigWhereUniqueInput
}

export type GigUpdateOneRequiredWithoutOrdersNestedInput = {
  create?: Prisma.XOR<Prisma.GigCreateWithoutOrdersInput, Prisma.GigUncheckedCreateWithoutOrdersInput>
  connectOrCreate?: Prisma.GigCreateOrConnectWithoutOrdersInput
  upsert?: Prisma.GigUpsertWithoutOrdersInput
  connect?: Prisma.GigWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.GigUpdateToOneWithWhereWithoutOrdersInput, Prisma.GigUpdateWithoutOrdersInput>, Prisma.GigUncheckedUpdateWithoutOrdersInput>
}

export type GigCreateWithoutUserInput = {
  id?: string
  title: string
  description: string
  price_basic: runtime.Decimal | runtime.DecimalJsLike | number | string
  price_standard: runtime.Decimal | runtime.DecimalJsLike | number | string
  price_premium: runtime.Decimal | runtime.DecimalJsLike | number | string
  delivery_days: number
  revisions: number
  thumbnail?: string | null
  images?: string | null
  status?: string
  created_at?: Date | string
  category: Prisma.CategoryCreateNestedOneWithoutGigsInput
  orders?: Prisma.OrderCreateNestedManyWithoutGigInput
}

export type GigUncheckedCreateWithoutUserInput = {
  id?: string
  title: string
  description: string
  category_id: string
  price_basic: runtime.Decimal | runtime.DecimalJsLike | number | string
  price_standard: runtime.Decimal | runtime.DecimalJsLike | number | string
  price_premium: runtime.Decimal | runtime.DecimalJsLike | number | string
  delivery_days: number
  revisions: number
  thumbnail?: string | null
  images?: string | null
  status?: string
  created_at?: Date | string
  orders?: Prisma.OrderUncheckedCreateNestedManyWithoutGigInput
}

export type GigCreateOrConnectWithoutUserInput = {
  where: Prisma.GigWhereUniqueInput
  create: Prisma.XOR<Prisma.GigCreateWithoutUserInput, Prisma.GigUncheckedCreateWithoutUserInput>
}

export type GigCreateManyUserInputEnvelope = {
  data: Prisma.GigCreateManyUserInput | Prisma.GigCreateManyUserInput[]
  skipDuplicates?: boolean
}

export type GigUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.GigWhereUniqueInput
  update: Prisma.XOR<Prisma.GigUpdateWithoutUserInput, Prisma.GigUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.GigCreateWithoutUserInput, Prisma.GigUncheckedCreateWithoutUserInput>
}

export type GigUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.GigWhereUniqueInput
  data: Prisma.XOR<Prisma.GigUpdateWithoutUserInput, Prisma.GigUncheckedUpdateWithoutUserInput>
}

export type GigUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.GigScalarWhereInput
  data: Prisma.XOR<Prisma.GigUpdateManyMutationInput, Prisma.GigUncheckedUpdateManyWithoutUserInput>
}

export type GigScalarWhereInput = {
  AND?: Prisma.GigScalarWhereInput | Prisma.GigScalarWhereInput[]
  OR?: Prisma.GigScalarWhereInput[]
  NOT?: Prisma.GigScalarWhereInput | Prisma.GigScalarWhereInput[]
  id?: Prisma.StringFilter<"Gig"> | string
  user_id?: Prisma.StringFilter<"Gig"> | string
  title?: Prisma.StringFilter<"Gig"> | string
  description?: Prisma.StringFilter<"Gig"> | string
  category_id?: Prisma.StringFilter<"Gig"> | string
  price_basic?: Prisma.DecimalFilter<"Gig"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  price_standard?: Prisma.DecimalFilter<"Gig"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  price_premium?: Prisma.DecimalFilter<"Gig"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  delivery_days?: Prisma.IntFilter<"Gig"> | number
  revisions?: Prisma.IntFilter<"Gig"> | number
  thumbnail?: Prisma.StringNullableFilter<"Gig"> | string | null
  images?: Prisma.StringNullableFilter<"Gig"> | string | null
  status?: Prisma.StringFilter<"Gig"> | string
  created_at?: Prisma.DateTimeFilter<"Gig"> | Date | string
}

export type GigCreateWithoutCategoryInput = {
  id?: string
  title: string
  description: string
  price_basic: runtime.Decimal | runtime.DecimalJsLike | number | string
  price_standard: runtime.Decimal | runtime.DecimalJsLike | number | string
  price_premium: runtime.Decimal | runtime.DecimalJsLike | number | string
  delivery_days: number
  revisions: number
  thumbnail?: string | null
  images?: string | null
  status?: string
  created_at?: Date | string
  user: Prisma.UserCreateNestedOneWithoutGigsInput
  orders?: Prisma.OrderCreateNestedManyWithoutGigInput
}

export type GigUncheckedCreateWithoutCategoryInput = {
  id?: string
  user_id: string
  title: string
  description: string
  price_basic: runtime.Decimal | runtime.DecimalJsLike | number | string
  price_standard: runtime.Decimal | runtime.DecimalJsLike | number | string
  price_premium: runtime.Decimal | runtime.DecimalJsLike | number | string
  delivery_days: number
  revisions: number
  thumbnail?: string | null
  images?: string | null
  status?: string
  created_at?: Date | string
  orders?: Prisma.OrderUncheckedCreateNestedManyWithoutGigInput
}

export type GigCreateOrConnectWithoutCategoryInput = {
  where: Prisma.GigWhereUniqueInput
  create: Prisma.XOR<Prisma.GigCreateWithoutCategoryInput, Prisma.GigUncheckedCreateWithoutCategoryInput>
}

export type GigCreateManyCategoryInputEnvelope = {
  data: Prisma.GigCreateManyCategoryInput | Prisma.GigCreateManyCategoryInput[]
  skipDuplicates?: boolean
}

export type GigUpsertWithWhereUniqueWithoutCategoryInput = {
  where: Prisma.GigWhereUniqueInput
  update: Prisma.XOR<Prisma.GigUpdateWithoutCategoryInput, Prisma.GigUncheckedUpdateWithoutCategoryInput>
  create: Prisma.XOR<Prisma.GigCreateWithoutCategoryInput, Prisma.GigUncheckedCreateWithoutCategoryInput>
}

export type GigUpdateWithWhereUniqueWithoutCategoryInput = {
  where: Prisma.GigWhereUniqueInput
  data: Prisma.XOR<Prisma.GigUpdateWithoutCategoryInput, Prisma.GigUncheckedUpdateWithoutCategoryInput>
}

export type GigUpdateManyWithWhereWithoutCategoryInput = {
  where: Prisma.GigScalarWhereInput
  data: Prisma.XOR<Prisma.GigUpdateManyMutationInput, Prisma.GigUncheckedUpdateManyWithoutCategoryInput>
}

export type GigCreateWithoutOrdersInput = {
  id?: string
  title: string
  description: string
  price_basic: runtime.Decimal | runtime.DecimalJsLike | number | string
  price_standard: runtime.Decimal | runtime.DecimalJsLike | number | string
  price_premium: runtime.Decimal | runtime.DecimalJsLike | number | string
  delivery_days: number
  revisions: number
  thumbnail?: string | null
  images?: string | null
  status?: string
  created_at?: Date | string
  user: Prisma.UserCreateNestedOneWithoutGigsInput
  category: Prisma.CategoryCreateNestedOneWithoutGigsInput
}

export type GigUncheckedCreateWithoutOrdersInput = {
  id?: string
  user_id: string
  title: string
  description: string
  category_id: string
  price_basic: runtime.Decimal | runtime.DecimalJsLike | number | string
  price_standard: runtime.Decimal | runtime.DecimalJsLike | number | string
  price_premium: runtime.Decimal | runtime.DecimalJsLike | number | string
  delivery_days: number
  revisions: number
  thumbnail?: string | null
  images?: string | null
  status?: string
  created_at?: Date | string
}

export type GigCreateOrConnectWithoutOrdersInput = {
  where: Prisma.GigWhereUniqueInput
  create: Prisma.XOR<Prisma.GigCreateWithoutOrdersInput, Prisma.GigUncheckedCreateWithoutOrdersInput>
}

export type GigUpsertWithoutOrdersInput = {
  update: Prisma.XOR<Prisma.GigUpdateWithoutOrdersInput, Prisma.GigUncheckedUpdateWithoutOrdersInput>
  create: Prisma.XOR<Prisma.GigCreateWithoutOrdersInput, Prisma.GigUncheckedCreateWithoutOrdersInput>
  where?: Prisma.GigWhereInput
}

export type GigUpdateToOneWithWhereWithoutOrdersInput = {
  where?: Prisma.GigWhereInput
  data: Prisma.XOR<Prisma.GigUpdateWithoutOrdersInput, Prisma.GigUncheckedUpdateWithoutOrdersInput>
}

export type GigUpdateWithoutOrdersInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  price_basic?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  price_standard?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  price_premium?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  delivery_days?: Prisma.IntFieldUpdateOperationsInput | number
  revisions?: Prisma.IntFieldUpdateOperationsInput | number
  thumbnail?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  images?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutGigsNestedInput
  category?: Prisma.CategoryUpdateOneRequiredWithoutGigsNestedInput
}

export type GigUncheckedUpdateWithoutOrdersInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  user_id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  category_id?: Prisma.StringFieldUpdateOperationsInput | string
  price_basic?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  price_standard?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  price_premium?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  delivery_days?: Prisma.IntFieldUpdateOperationsInput | number
  revisions?: Prisma.IntFieldUpdateOperationsInput | number
  thumbnail?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  images?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type GigCreateManyUserInput = {
  id?: string
  title: string
  description: string
  category_id: string
  price_basic: runtime.Decimal | runtime.DecimalJsLike | number | string
  price_standard: runtime.Decimal | runtime.DecimalJsLike | number | string
  price_premium: runtime.Decimal | runtime.DecimalJsLike | number | string
  delivery_days: number
  revisions: number
  thumbnail?: string | null
  images?: string | null
  status?: string
  created_at?: Date | string
}

export type GigUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  price_basic?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  price_standard?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  price_premium?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  delivery_days?: Prisma.IntFieldUpdateOperationsInput | number
  revisions?: Prisma.IntFieldUpdateOperationsInput | number
  thumbnail?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  images?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  category?: Prisma.CategoryUpdateOneRequiredWithoutGigsNestedInput
  orders?: Prisma.OrderUpdateManyWithoutGigNestedInput
}

export type GigUncheckedUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  category_id?: Prisma.StringFieldUpdateOperationsInput | string
  price_basic?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  price_standard?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  price_premium?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  delivery_days?: Prisma.IntFieldUpdateOperationsInput | number
  revisions?: Prisma.IntFieldUpdateOperationsInput | number
  thumbnail?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  images?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  orders?: Prisma.OrderUncheckedUpdateManyWithoutGigNestedInput
}

export type GigUncheckedUpdateManyWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  category_id?: Prisma.StringFieldUpdateOperationsInput | string
  price_basic?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  price_standard?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  price_premium?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  delivery_days?: Prisma.IntFieldUpdateOperationsInput | number
  revisions?: Prisma.IntFieldUpdateOperationsInput | number
  thumbnail?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  images?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type GigCreateManyCategoryInput = {
  id?: string
  user_id: string
  title: string
  description: string
  price_basic: runtime.Decimal | runtime.DecimalJsLike | number | string
  price_standard: runtime.Decimal | runtime.DecimalJsLike | number | string
  price_premium: runtime.Decimal | runtime.DecimalJsLike | number | string
  delivery_days: number
  revisions: number
  thumbnail?: string | null
  images?: string | null
  status?: string
  created_at?: Date | string
}

export type GigUpdateWithoutCategoryInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  price_basic?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  price_standard?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  price_premium?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  delivery_days?: Prisma.IntFieldUpdateOperationsInput | number
  revisions?: Prisma.IntFieldUpdateOperationsInput | number
  thumbnail?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  images?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutGigsNestedInput
  orders?: Prisma.OrderUpdateManyWithoutGigNestedInput
}

export type GigUncheckedUpdateWithoutCategoryInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  user_id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  price_basic?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  price_standard?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  price_premium?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  delivery_days?: Prisma.IntFieldUpdateOperationsInput | number
  revisions?: Prisma.IntFieldUpdateOperationsInput | number
  thumbnail?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  images?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  orders?: Prisma.OrderUncheckedUpdateManyWithoutGigNestedInput
}

export type GigUncheckedUpdateManyWithoutCategoryInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  user_id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  price_basic?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  price_standard?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  price_premium?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  delivery_days?: Prisma.IntFieldUpdateOperationsInput | number
  revisions?: Prisma.IntFieldUpdateOperationsInput | number
  thumbnail?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  images?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}


/**
 * Count Type GigCountOutputType
 */

export type GigCountOutputType = {
  orders: number
}

export type GigCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  orders?: boolean | GigCountOutputTypeCountOrdersArgs
}

/**
 * GigCountOutputType without action
 */
export type GigCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GigCountOutputType
   */
  select?: Prisma.GigCountOutputTypeSelect<ExtArgs> | null
}

/**
 * GigCountOutputType without action
 */
export type GigCountOutputTypeCountOrdersArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.OrderWhereInput
}


export type GigSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  user_id?: boolean
  title?: boolean
  description?: boolean
  category_id?: boolean
  price_basic?: boolean
  price_standard?: boolean
  price_premium?: boolean
  delivery_days?: boolean
  revisions?: boolean
  thumbnail?: boolean
  images?: boolean
  status?: boolean
  created_at?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  category?: boolean | Prisma.CategoryDefaultArgs<ExtArgs>
  orders?: boolean | Prisma.Gig$ordersArgs<ExtArgs>
  _count?: boolean | Prisma.GigCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["gig"]>

export type GigSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  user_id?: boolean
  title?: boolean
  description?: boolean
  category_id?: boolean
  price_basic?: boolean
  price_standard?: boolean
  price_premium?: boolean
  delivery_days?: boolean
  revisions?: boolean
  thumbnail?: boolean
  images?: boolean
  status?: boolean
  created_at?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  category?: boolean | Prisma.CategoryDefaultArgs<ExtArgs>
}, ExtArgs["result"]["gig"]>

export type GigSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  user_id?: boolean
  title?: boolean
  description?: boolean
  category_id?: boolean
  price_basic?: boolean
  price_standard?: boolean
  price_premium?: boolean
  delivery_days?: boolean
  revisions?: boolean
  thumbnail?: boolean
  images?: boolean
  status?: boolean
  created_at?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  category?: boolean | Prisma.CategoryDefaultArgs<ExtArgs>
}, ExtArgs["result"]["gig"]>

export type GigSelectScalar = {
  id?: boolean
  user_id?: boolean
  title?: boolean
  description?: boolean
  category_id?: boolean
  price_basic?: boolean
  price_standard?: boolean
  price_premium?: boolean
  delivery_days?: boolean
  revisions?: boolean
  thumbnail?: boolean
  images?: boolean
  status?: boolean
  created_at?: boolean
}

export type GigOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "user_id" | "title" | "description" | "category_id" | "price_basic" | "price_standard" | "price_premium" | "delivery_days" | "revisions" | "thumbnail" | "images" | "status" | "created_at", ExtArgs["result"]["gig"]>
export type GigInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  category?: boolean | Prisma.CategoryDefaultArgs<ExtArgs>
  orders?: boolean | Prisma.Gig$ordersArgs<ExtArgs>
  _count?: boolean | Prisma.GigCountOutputTypeDefaultArgs<ExtArgs>
}
export type GigIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  category?: boolean | Prisma.CategoryDefaultArgs<ExtArgs>
}
export type GigIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  category?: boolean | Prisma.CategoryDefaultArgs<ExtArgs>
}

export type $GigPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Gig"
  objects: {
    user: Prisma.$UserPayload<ExtArgs>
    category: Prisma.$CategoryPayload<ExtArgs>
    orders: Prisma.$OrderPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    user_id: string
    title: string
    description: string
    category_id: string
    price_basic: runtime.Decimal
    price_standard: runtime.Decimal
    price_premium: runtime.Decimal
    delivery_days: number
    revisions: number
    thumbnail: string | null
    images: string | null
    status: string
    created_at: Date
  }, ExtArgs["result"]["gig"]>
  composites: {}
}

export type GigGetPayload<S extends boolean | null | undefined | GigDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$GigPayload, S>

export type GigCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<GigFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: GigCountAggregateInputType | true
  }

export interface GigDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Gig'], meta: { name: 'Gig' } }
  /**
   * Find zero or one Gig that matches the filter.
   * @param {GigFindUniqueArgs} args - Arguments to find a Gig
   * @example
   * // Get one Gig
   * const gig = await prisma.gig.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends GigFindUniqueArgs>(args: Prisma.SelectSubset<T, GigFindUniqueArgs<ExtArgs>>): Prisma.Prisma__GigClient<runtime.Types.Result.GetResult<Prisma.$GigPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Gig that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {GigFindUniqueOrThrowArgs} args - Arguments to find a Gig
   * @example
   * // Get one Gig
   * const gig = await prisma.gig.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends GigFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, GigFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__GigClient<runtime.Types.Result.GetResult<Prisma.$GigPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Gig that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {GigFindFirstArgs} args - Arguments to find a Gig
   * @example
   * // Get one Gig
   * const gig = await prisma.gig.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends GigFindFirstArgs>(args?: Prisma.SelectSubset<T, GigFindFirstArgs<ExtArgs>>): Prisma.Prisma__GigClient<runtime.Types.Result.GetResult<Prisma.$GigPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Gig that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {GigFindFirstOrThrowArgs} args - Arguments to find a Gig
   * @example
   * // Get one Gig
   * const gig = await prisma.gig.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends GigFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, GigFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__GigClient<runtime.Types.Result.GetResult<Prisma.$GigPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Gigs that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {GigFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Gigs
   * const gigs = await prisma.gig.findMany()
   * 
   * // Get first 10 Gigs
   * const gigs = await prisma.gig.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const gigWithIdOnly = await prisma.gig.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends GigFindManyArgs>(args?: Prisma.SelectSubset<T, GigFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$GigPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Gig.
   * @param {GigCreateArgs} args - Arguments to create a Gig.
   * @example
   * // Create one Gig
   * const Gig = await prisma.gig.create({
   *   data: {
   *     // ... data to create a Gig
   *   }
   * })
   * 
   */
  create<T extends GigCreateArgs>(args: Prisma.SelectSubset<T, GigCreateArgs<ExtArgs>>): Prisma.Prisma__GigClient<runtime.Types.Result.GetResult<Prisma.$GigPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Gigs.
   * @param {GigCreateManyArgs} args - Arguments to create many Gigs.
   * @example
   * // Create many Gigs
   * const gig = await prisma.gig.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends GigCreateManyArgs>(args?: Prisma.SelectSubset<T, GigCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Gigs and returns the data saved in the database.
   * @param {GigCreateManyAndReturnArgs} args - Arguments to create many Gigs.
   * @example
   * // Create many Gigs
   * const gig = await prisma.gig.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Gigs and only return the `id`
   * const gigWithIdOnly = await prisma.gig.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends GigCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, GigCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$GigPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Gig.
   * @param {GigDeleteArgs} args - Arguments to delete one Gig.
   * @example
   * // Delete one Gig
   * const Gig = await prisma.gig.delete({
   *   where: {
   *     // ... filter to delete one Gig
   *   }
   * })
   * 
   */
  delete<T extends GigDeleteArgs>(args: Prisma.SelectSubset<T, GigDeleteArgs<ExtArgs>>): Prisma.Prisma__GigClient<runtime.Types.Result.GetResult<Prisma.$GigPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Gig.
   * @param {GigUpdateArgs} args - Arguments to update one Gig.
   * @example
   * // Update one Gig
   * const gig = await prisma.gig.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends GigUpdateArgs>(args: Prisma.SelectSubset<T, GigUpdateArgs<ExtArgs>>): Prisma.Prisma__GigClient<runtime.Types.Result.GetResult<Prisma.$GigPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Gigs.
   * @param {GigDeleteManyArgs} args - Arguments to filter Gigs to delete.
   * @example
   * // Delete a few Gigs
   * const { count } = await prisma.gig.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends GigDeleteManyArgs>(args?: Prisma.SelectSubset<T, GigDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Gigs.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {GigUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Gigs
   * const gig = await prisma.gig.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends GigUpdateManyArgs>(args: Prisma.SelectSubset<T, GigUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Gigs and returns the data updated in the database.
   * @param {GigUpdateManyAndReturnArgs} args - Arguments to update many Gigs.
   * @example
   * // Update many Gigs
   * const gig = await prisma.gig.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Gigs and only return the `id`
   * const gigWithIdOnly = await prisma.gig.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends GigUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, GigUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$GigPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Gig.
   * @param {GigUpsertArgs} args - Arguments to update or create a Gig.
   * @example
   * // Update or create a Gig
   * const gig = await prisma.gig.upsert({
   *   create: {
   *     // ... data to create a Gig
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Gig we want to update
   *   }
   * })
   */
  upsert<T extends GigUpsertArgs>(args: Prisma.SelectSubset<T, GigUpsertArgs<ExtArgs>>): Prisma.Prisma__GigClient<runtime.Types.Result.GetResult<Prisma.$GigPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Gigs.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {GigCountArgs} args - Arguments to filter Gigs to count.
   * @example
   * // Count the number of Gigs
   * const count = await prisma.gig.count({
   *   where: {
   *     // ... the filter for the Gigs we want to count
   *   }
   * })
  **/
  count<T extends GigCountArgs>(
    args?: Prisma.Subset<T, GigCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], GigCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Gig.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {GigAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends GigAggregateArgs>(args: Prisma.Subset<T, GigAggregateArgs>): Prisma.PrismaPromise<GetGigAggregateType<T>>

  /**
   * Group by Gig.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {GigGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends GigGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: GigGroupByArgs['orderBy'] }
      : { orderBy?: GigGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, GigGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetGigGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Gig model
 */
readonly fields: GigFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Gig.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__GigClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  user<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  category<T extends Prisma.CategoryDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.CategoryDefaultArgs<ExtArgs>>): Prisma.Prisma__CategoryClient<runtime.Types.Result.GetResult<Prisma.$CategoryPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  orders<T extends Prisma.Gig$ordersArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Gig$ordersArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$OrderPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Gig model
 */
export interface GigFieldRefs {
  readonly id: Prisma.FieldRef<"Gig", 'String'>
  readonly user_id: Prisma.FieldRef<"Gig", 'String'>
  readonly title: Prisma.FieldRef<"Gig", 'String'>
  readonly description: Prisma.FieldRef<"Gig", 'String'>
  readonly category_id: Prisma.FieldRef<"Gig", 'String'>
  readonly price_basic: Prisma.FieldRef<"Gig", 'Decimal'>
  readonly price_standard: Prisma.FieldRef<"Gig", 'Decimal'>
  readonly price_premium: Prisma.FieldRef<"Gig", 'Decimal'>
  readonly delivery_days: Prisma.FieldRef<"Gig", 'Int'>
  readonly revisions: Prisma.FieldRef<"Gig", 'Int'>
  readonly thumbnail: Prisma.FieldRef<"Gig", 'String'>
  readonly images: Prisma.FieldRef<"Gig", 'String'>
  readonly status: Prisma.FieldRef<"Gig", 'String'>
  readonly created_at: Prisma.FieldRef<"Gig", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Gig findUnique
 */
export type GigFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Gig
   */
  select?: Prisma.GigSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Gig
   */
  omit?: Prisma.GigOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GigInclude<ExtArgs> | null
  /**
   * Filter, which Gig to fetch.
   */
  where: Prisma.GigWhereUniqueInput
}

/**
 * Gig findUniqueOrThrow
 */
export type GigFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Gig
   */
  select?: Prisma.GigSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Gig
   */
  omit?: Prisma.GigOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GigInclude<ExtArgs> | null
  /**
   * Filter, which Gig to fetch.
   */
  where: Prisma.GigWhereUniqueInput
}

/**
 * Gig findFirst
 */
export type GigFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Gig
   */
  select?: Prisma.GigSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Gig
   */
  omit?: Prisma.GigOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GigInclude<ExtArgs> | null
  /**
   * Filter, which Gig to fetch.
   */
  where?: Prisma.GigWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Gigs to fetch.
   */
  orderBy?: Prisma.GigOrderByWithRelationInput | Prisma.GigOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Gigs.
   */
  cursor?: Prisma.GigWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Gigs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Gigs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Gigs.
   */
  distinct?: Prisma.GigScalarFieldEnum | Prisma.GigScalarFieldEnum[]
}

/**
 * Gig findFirstOrThrow
 */
export type GigFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Gig
   */
  select?: Prisma.GigSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Gig
   */
  omit?: Prisma.GigOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GigInclude<ExtArgs> | null
  /**
   * Filter, which Gig to fetch.
   */
  where?: Prisma.GigWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Gigs to fetch.
   */
  orderBy?: Prisma.GigOrderByWithRelationInput | Prisma.GigOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Gigs.
   */
  cursor?: Prisma.GigWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Gigs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Gigs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Gigs.
   */
  distinct?: Prisma.GigScalarFieldEnum | Prisma.GigScalarFieldEnum[]
}

/**
 * Gig findMany
 */
export type GigFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Gig
   */
  select?: Prisma.GigSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Gig
   */
  omit?: Prisma.GigOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GigInclude<ExtArgs> | null
  /**
   * Filter, which Gigs to fetch.
   */
  where?: Prisma.GigWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Gigs to fetch.
   */
  orderBy?: Prisma.GigOrderByWithRelationInput | Prisma.GigOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Gigs.
   */
  cursor?: Prisma.GigWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Gigs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Gigs.
   */
  skip?: number
  distinct?: Prisma.GigScalarFieldEnum | Prisma.GigScalarFieldEnum[]
}

/**
 * Gig create
 */
export type GigCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Gig
   */
  select?: Prisma.GigSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Gig
   */
  omit?: Prisma.GigOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GigInclude<ExtArgs> | null
  /**
   * The data needed to create a Gig.
   */
  data: Prisma.XOR<Prisma.GigCreateInput, Prisma.GigUncheckedCreateInput>
}

/**
 * Gig createMany
 */
export type GigCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Gigs.
   */
  data: Prisma.GigCreateManyInput | Prisma.GigCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Gig createManyAndReturn
 */
export type GigCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Gig
   */
  select?: Prisma.GigSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Gig
   */
  omit?: Prisma.GigOmit<ExtArgs> | null
  /**
   * The data used to create many Gigs.
   */
  data: Prisma.GigCreateManyInput | Prisma.GigCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GigIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Gig update
 */
export type GigUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Gig
   */
  select?: Prisma.GigSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Gig
   */
  omit?: Prisma.GigOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GigInclude<ExtArgs> | null
  /**
   * The data needed to update a Gig.
   */
  data: Prisma.XOR<Prisma.GigUpdateInput, Prisma.GigUncheckedUpdateInput>
  /**
   * Choose, which Gig to update.
   */
  where: Prisma.GigWhereUniqueInput
}

/**
 * Gig updateMany
 */
export type GigUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Gigs.
   */
  data: Prisma.XOR<Prisma.GigUpdateManyMutationInput, Prisma.GigUncheckedUpdateManyInput>
  /**
   * Filter which Gigs to update
   */
  where?: Prisma.GigWhereInput
  /**
   * Limit how many Gigs to update.
   */
  limit?: number
}

/**
 * Gig updateManyAndReturn
 */
export type GigUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Gig
   */
  select?: Prisma.GigSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Gig
   */
  omit?: Prisma.GigOmit<ExtArgs> | null
  /**
   * The data used to update Gigs.
   */
  data: Prisma.XOR<Prisma.GigUpdateManyMutationInput, Prisma.GigUncheckedUpdateManyInput>
  /**
   * Filter which Gigs to update
   */
  where?: Prisma.GigWhereInput
  /**
   * Limit how many Gigs to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GigIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Gig upsert
 */
export type GigUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Gig
   */
  select?: Prisma.GigSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Gig
   */
  omit?: Prisma.GigOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GigInclude<ExtArgs> | null
  /**
   * The filter to search for the Gig to update in case it exists.
   */
  where: Prisma.GigWhereUniqueInput
  /**
   * In case the Gig found by the `where` argument doesn't exist, create a new Gig with this data.
   */
  create: Prisma.XOR<Prisma.GigCreateInput, Prisma.GigUncheckedCreateInput>
  /**
   * In case the Gig was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.GigUpdateInput, Prisma.GigUncheckedUpdateInput>
}

/**
 * Gig delete
 */
export type GigDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Gig
   */
  select?: Prisma.GigSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Gig
   */
  omit?: Prisma.GigOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GigInclude<ExtArgs> | null
  /**
   * Filter which Gig to delete.
   */
  where: Prisma.GigWhereUniqueInput
}

/**
 * Gig deleteMany
 */
export type GigDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Gigs to delete
   */
  where?: Prisma.GigWhereInput
  /**
   * Limit how many Gigs to delete.
   */
  limit?: number
}

/**
 * Gig.orders
 */
export type Gig$ordersArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Order
   */
  select?: Prisma.OrderSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Order
   */
  omit?: Prisma.OrderOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OrderInclude<ExtArgs> | null
  where?: Prisma.OrderWhereInput
  orderBy?: Prisma.OrderOrderByWithRelationInput | Prisma.OrderOrderByWithRelationInput[]
  cursor?: Prisma.OrderWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.OrderScalarFieldEnum | Prisma.OrderScalarFieldEnum[]
}

/**
 * Gig without action
 */
export type GigDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Gig
   */
  select?: Prisma.GigSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Gig
   */
  omit?: Prisma.GigOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GigInclude<ExtArgs> | null
}
