
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// @ts-nocheck 
/*
 * This file exports the `Order` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model Order
 * 
 */
export type OrderModel = runtime.Types.Result.DefaultSelection<Prisma.$OrderPayload>

export type AggregateOrder = {
  _count: OrderCountAggregateOutputType | null
  _avg: OrderAvgAggregateOutputType | null
  _sum: OrderSumAggregateOutputType | null
  _min: OrderMinAggregateOutputType | null
  _max: OrderMaxAggregateOutputType | null
}

export type OrderAvgAggregateOutputType = {
  amount: runtime.Decimal | null
}

export type OrderSumAggregateOutputType = {
  amount: runtime.Decimal | null
}

export type OrderMinAggregateOutputType = {
  id: string | null
  buyer_id: string | null
  seller_id: string | null
  gig_id: string | null
  status: string | null
  amount: runtime.Decimal | null
  delivery_date: Date | null
  created_at: Date | null
  updated_at: Date | null
}

export type OrderMaxAggregateOutputType = {
  id: string | null
  buyer_id: string | null
  seller_id: string | null
  gig_id: string | null
  status: string | null
  amount: runtime.Decimal | null
  delivery_date: Date | null
  created_at: Date | null
  updated_at: Date | null
}

export type OrderCountAggregateOutputType = {
  id: number
  buyer_id: number
  seller_id: number
  gig_id: number
  status: number
  amount: number
  delivery_date: number
  created_at: number
  updated_at: number
  _all: number
}


export type OrderAvgAggregateInputType = {
  amount?: true
}

export type OrderSumAggregateInputType = {
  amount?: true
}

export type OrderMinAggregateInputType = {
  id?: true
  buyer_id?: true
  seller_id?: true
  gig_id?: true
  status?: true
  amount?: true
  delivery_date?: true
  created_at?: true
  updated_at?: true
}

export type OrderMaxAggregateInputType = {
  id?: true
  buyer_id?: true
  seller_id?: true
  gig_id?: true
  status?: true
  amount?: true
  delivery_date?: true
  created_at?: true
  updated_at?: true
}

export type OrderCountAggregateInputType = {
  id?: true
  buyer_id?: true
  seller_id?: true
  gig_id?: true
  status?: true
  amount?: true
  delivery_date?: true
  created_at?: true
  updated_at?: true
  _all?: true
}

export type OrderAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Order to aggregate.
   */
  where?: Prisma.OrderWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Orders to fetch.
   */
  orderBy?: Prisma.OrderOrderByWithRelationInput | Prisma.OrderOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.OrderWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Orders from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Orders.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Orders
  **/
  _count?: true | OrderCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: OrderAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: OrderSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: OrderMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: OrderMaxAggregateInputType
}

export type GetOrderAggregateType<T extends OrderAggregateArgs> = {
      [P in keyof T & keyof AggregateOrder]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateOrder[P]>
    : Prisma.GetScalarType<T[P], AggregateOrder[P]>
}




export type OrderGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.OrderWhereInput
  orderBy?: Prisma.OrderOrderByWithAggregationInput | Prisma.OrderOrderByWithAggregationInput[]
  by: Prisma.OrderScalarFieldEnum[] | Prisma.OrderScalarFieldEnum
  having?: Prisma.OrderScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: OrderCountAggregateInputType | true
  _avg?: OrderAvgAggregateInputType
  _sum?: OrderSumAggregateInputType
  _min?: OrderMinAggregateInputType
  _max?: OrderMaxAggregateInputType
}

export type OrderGroupByOutputType = {
  id: string
  buyer_id: string
  seller_id: string
  gig_id: string
  status: string
  amount: runtime.Decimal
  delivery_date: Date | null
  created_at: Date
  updated_at: Date
  _count: OrderCountAggregateOutputType | null
  _avg: OrderAvgAggregateOutputType | null
  _sum: OrderSumAggregateOutputType | null
  _min: OrderMinAggregateOutputType | null
  _max: OrderMaxAggregateOutputType | null
}

type GetOrderGroupByPayload<T extends OrderGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<OrderGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof OrderGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], OrderGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], OrderGroupByOutputType[P]>
      }
    >
  >



export type OrderWhereInput = {
  AND?: Prisma.OrderWhereInput | Prisma.OrderWhereInput[]
  OR?: Prisma.OrderWhereInput[]
  NOT?: Prisma.OrderWhereInput | Prisma.OrderWhereInput[]
  id?: Prisma.StringFilter<"Order"> | string
  buyer_id?: Prisma.StringFilter<"Order"> | string
  seller_id?: Prisma.StringFilter<"Order"> | string
  gig_id?: Prisma.StringFilter<"Order"> | string
  status?: Prisma.StringFilter<"Order"> | string
  amount?: Prisma.DecimalFilter<"Order"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  delivery_date?: Prisma.DateTimeNullableFilter<"Order"> | Date | string | null
  created_at?: Prisma.DateTimeFilter<"Order"> | Date | string
  updated_at?: Prisma.DateTimeFilter<"Order"> | Date | string
  buyer?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  seller?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  gig?: Prisma.XOR<Prisma.GigScalarRelationFilter, Prisma.GigWhereInput>
  reviews?: Prisma.ReviewListRelationFilter
  disputes?: Prisma.DisputeListRelationFilter
}

export type OrderOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  buyer_id?: Prisma.SortOrder
  seller_id?: Prisma.SortOrder
  gig_id?: Prisma.SortOrder
  status?: Prisma.SortOrder
  amount?: Prisma.SortOrder
  delivery_date?: Prisma.SortOrderInput | Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  buyer?: Prisma.UserOrderByWithRelationInput
  seller?: Prisma.UserOrderByWithRelationInput
  gig?: Prisma.GigOrderByWithRelationInput
  reviews?: Prisma.ReviewOrderByRelationAggregateInput
  disputes?: Prisma.DisputeOrderByRelationAggregateInput
}

export type OrderWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.OrderWhereInput | Prisma.OrderWhereInput[]
  OR?: Prisma.OrderWhereInput[]
  NOT?: Prisma.OrderWhereInput | Prisma.OrderWhereInput[]
  buyer_id?: Prisma.StringFilter<"Order"> | string
  seller_id?: Prisma.StringFilter<"Order"> | string
  gig_id?: Prisma.StringFilter<"Order"> | string
  status?: Prisma.StringFilter<"Order"> | string
  amount?: Prisma.DecimalFilter<"Order"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  delivery_date?: Prisma.DateTimeNullableFilter<"Order"> | Date | string | null
  created_at?: Prisma.DateTimeFilter<"Order"> | Date | string
  updated_at?: Prisma.DateTimeFilter<"Order"> | Date | string
  buyer?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  seller?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  gig?: Prisma.XOR<Prisma.GigScalarRelationFilter, Prisma.GigWhereInput>
  reviews?: Prisma.ReviewListRelationFilter
  disputes?: Prisma.DisputeListRelationFilter
}, "id">

export type OrderOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  buyer_id?: Prisma.SortOrder
  seller_id?: Prisma.SortOrder
  gig_id?: Prisma.SortOrder
  status?: Prisma.SortOrder
  amount?: Prisma.SortOrder
  delivery_date?: Prisma.SortOrderInput | Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  _count?: Prisma.OrderCountOrderByAggregateInput
  _avg?: Prisma.OrderAvgOrderByAggregateInput
  _max?: Prisma.OrderMaxOrderByAggregateInput
  _min?: Prisma.OrderMinOrderByAggregateInput
  _sum?: Prisma.OrderSumOrderByAggregateInput
}

export type OrderScalarWhereWithAggregatesInput = {
  AND?: Prisma.OrderScalarWhereWithAggregatesInput | Prisma.OrderScalarWhereWithAggregatesInput[]
  OR?: Prisma.OrderScalarWhereWithAggregatesInput[]
  NOT?: Prisma.OrderScalarWhereWithAggregatesInput | Prisma.OrderScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Order"> | string
  buyer_id?: Prisma.StringWithAggregatesFilter<"Order"> | string
  seller_id?: Prisma.StringWithAggregatesFilter<"Order"> | string
  gig_id?: Prisma.StringWithAggregatesFilter<"Order"> | string
  status?: Prisma.StringWithAggregatesFilter<"Order"> | string
  amount?: Prisma.DecimalWithAggregatesFilter<"Order"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  delivery_date?: Prisma.DateTimeNullableWithAggregatesFilter<"Order"> | Date | string | null
  created_at?: Prisma.DateTimeWithAggregatesFilter<"Order"> | Date | string
  updated_at?: Prisma.DateTimeWithAggregatesFilter<"Order"> | Date | string
}

export type OrderCreateInput = {
  id?: string
  status?: string
  amount: runtime.Decimal | runtime.DecimalJsLike | number | string
  delivery_date?: Date | string | null
  created_at?: Date | string
  updated_at?: Date | string
  buyer: Prisma.UserCreateNestedOneWithoutOrdersBuyerInput
  seller: Prisma.UserCreateNestedOneWithoutOrdersSellerInput
  gig: Prisma.GigCreateNestedOneWithoutOrdersInput
  reviews?: Prisma.ReviewCreateNestedManyWithoutOrderInput
  disputes?: Prisma.DisputeCreateNestedManyWithoutOrderInput
}

export type OrderUncheckedCreateInput = {
  id?: string
  buyer_id: string
  seller_id: string
  gig_id: string
  status?: string
  amount: runtime.Decimal | runtime.DecimalJsLike | number | string
  delivery_date?: Date | string | null
  created_at?: Date | string
  updated_at?: Date | string
  reviews?: Prisma.ReviewUncheckedCreateNestedManyWithoutOrderInput
  disputes?: Prisma.DisputeUncheckedCreateNestedManyWithoutOrderInput
}

export type OrderUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  amount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  delivery_date?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  buyer?: Prisma.UserUpdateOneRequiredWithoutOrdersBuyerNestedInput
  seller?: Prisma.UserUpdateOneRequiredWithoutOrdersSellerNestedInput
  gig?: Prisma.GigUpdateOneRequiredWithoutOrdersNestedInput
  reviews?: Prisma.ReviewUpdateManyWithoutOrderNestedInput
  disputes?: Prisma.DisputeUpdateManyWithoutOrderNestedInput
}

export type OrderUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  buyer_id?: Prisma.StringFieldUpdateOperationsInput | string
  seller_id?: Prisma.StringFieldUpdateOperationsInput | string
  gig_id?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  amount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  delivery_date?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  reviews?: Prisma.ReviewUncheckedUpdateManyWithoutOrderNestedInput
  disputes?: Prisma.DisputeUncheckedUpdateManyWithoutOrderNestedInput
}

export type OrderCreateManyInput = {
  id?: string
  buyer_id: string
  seller_id: string
  gig_id: string
  status?: string
  amount: runtime.Decimal | runtime.DecimalJsLike | number | string
  delivery_date?: Date | string | null
  created_at?: Date | string
  updated_at?: Date | string
}

export type OrderUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  amount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  delivery_date?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type OrderUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  buyer_id?: Prisma.StringFieldUpdateOperationsInput | string
  seller_id?: Prisma.StringFieldUpdateOperationsInput | string
  gig_id?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  amount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  delivery_date?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type OrderListRelationFilter = {
  every?: Prisma.OrderWhereInput
  some?: Prisma.OrderWhereInput
  none?: Prisma.OrderWhereInput
}

export type OrderOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type OrderCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  buyer_id?: Prisma.SortOrder
  seller_id?: Prisma.SortOrder
  gig_id?: Prisma.SortOrder
  status?: Prisma.SortOrder
  amount?: Prisma.SortOrder
  delivery_date?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
}

export type OrderAvgOrderByAggregateInput = {
  amount?: Prisma.SortOrder
}

export type OrderMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  buyer_id?: Prisma.SortOrder
  seller_id?: Prisma.SortOrder
  gig_id?: Prisma.SortOrder
  status?: Prisma.SortOrder
  amount?: Prisma.SortOrder
  delivery_date?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
}

export type OrderMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  buyer_id?: Prisma.SortOrder
  seller_id?: Prisma.SortOrder
  gig_id?: Prisma.SortOrder
  status?: Prisma.SortOrder
  amount?: Prisma.SortOrder
  delivery_date?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
}

export type OrderSumOrderByAggregateInput = {
  amount?: Prisma.SortOrder
}

export type OrderScalarRelationFilter = {
  is?: Prisma.OrderWhereInput
  isNot?: Prisma.OrderWhereInput
}

export type OrderCreateNestedManyWithoutBuyerInput = {
  create?: Prisma.XOR<Prisma.OrderCreateWithoutBuyerInput, Prisma.OrderUncheckedCreateWithoutBuyerInput> | Prisma.OrderCreateWithoutBuyerInput[] | Prisma.OrderUncheckedCreateWithoutBuyerInput[]
  connectOrCreate?: Prisma.OrderCreateOrConnectWithoutBuyerInput | Prisma.OrderCreateOrConnectWithoutBuyerInput[]
  createMany?: Prisma.OrderCreateManyBuyerInputEnvelope
  connect?: Prisma.OrderWhereUniqueInput | Prisma.OrderWhereUniqueInput[]
}

export type OrderCreateNestedManyWithoutSellerInput = {
  create?: Prisma.XOR<Prisma.OrderCreateWithoutSellerInput, Prisma.OrderUncheckedCreateWithoutSellerInput> | Prisma.OrderCreateWithoutSellerInput[] | Prisma.OrderUncheckedCreateWithoutSellerInput[]
  connectOrCreate?: Prisma.OrderCreateOrConnectWithoutSellerInput | Prisma.OrderCreateOrConnectWithoutSellerInput[]
  createMany?: Prisma.OrderCreateManySellerInputEnvelope
  connect?: Prisma.OrderWhereUniqueInput | Prisma.OrderWhereUniqueInput[]
}

export type OrderUncheckedCreateNestedManyWithoutBuyerInput = {
  create?: Prisma.XOR<Prisma.OrderCreateWithoutBuyerInput, Prisma.OrderUncheckedCreateWithoutBuyerInput> | Prisma.OrderCreateWithoutBuyerInput[] | Prisma.OrderUncheckedCreateWithoutBuyerInput[]
  connectOrCreate?: Prisma.OrderCreateOrConnectWithoutBuyerInput | Prisma.OrderCreateOrConnectWithoutBuyerInput[]
  createMany?: Prisma.OrderCreateManyBuyerInputEnvelope
  connect?: Prisma.OrderWhereUniqueInput | Prisma.OrderWhereUniqueInput[]
}

export type OrderUncheckedCreateNestedManyWithoutSellerInput = {
  create?: Prisma.XOR<Prisma.OrderCreateWithoutSellerInput, Prisma.OrderUncheckedCreateWithoutSellerInput> | Prisma.OrderCreateWithoutSellerInput[] | Prisma.OrderUncheckedCreateWithoutSellerInput[]
  connectOrCreate?: Prisma.OrderCreateOrConnectWithoutSellerInput | Prisma.OrderCreateOrConnectWithoutSellerInput[]
  createMany?: Prisma.OrderCreateManySellerInputEnvelope
  connect?: Prisma.OrderWhereUniqueInput | Prisma.OrderWhereUniqueInput[]
}

export type OrderUpdateManyWithoutBuyerNestedInput = {
  create?: Prisma.XOR<Prisma.OrderCreateWithoutBuyerInput, Prisma.OrderUncheckedCreateWithoutBuyerInput> | Prisma.OrderCreateWithoutBuyerInput[] | Prisma.OrderUncheckedCreateWithoutBuyerInput[]
  connectOrCreate?: Prisma.OrderCreateOrConnectWithoutBuyerInput | Prisma.OrderCreateOrConnectWithoutBuyerInput[]
  upsert?: Prisma.OrderUpsertWithWhereUniqueWithoutBuyerInput | Prisma.OrderUpsertWithWhereUniqueWithoutBuyerInput[]
  createMany?: Prisma.OrderCreateManyBuyerInputEnvelope
  set?: Prisma.OrderWhereUniqueInput | Prisma.OrderWhereUniqueInput[]
  disconnect?: Prisma.OrderWhereUniqueInput | Prisma.OrderWhereUniqueInput[]
  delete?: Prisma.OrderWhereUniqueInput | Prisma.OrderWhereUniqueInput[]
  connect?: Prisma.OrderWhereUniqueInput | Prisma.OrderWhereUniqueInput[]
  update?: Prisma.OrderUpdateWithWhereUniqueWithoutBuyerInput | Prisma.OrderUpdateWithWhereUniqueWithoutBuyerInput[]
  updateMany?: Prisma.OrderUpdateManyWithWhereWithoutBuyerInput | Prisma.OrderUpdateManyWithWhereWithoutBuyerInput[]
  deleteMany?: Prisma.OrderScalarWhereInput | Prisma.OrderScalarWhereInput[]
}

export type OrderUpdateManyWithoutSellerNestedInput = {
  create?: Prisma.XOR<Prisma.OrderCreateWithoutSellerInput, Prisma.OrderUncheckedCreateWithoutSellerInput> | Prisma.OrderCreateWithoutSellerInput[] | Prisma.OrderUncheckedCreateWithoutSellerInput[]
  connectOrCreate?: Prisma.OrderCreateOrConnectWithoutSellerInput | Prisma.OrderCreateOrConnectWithoutSellerInput[]
  upsert?: Prisma.OrderUpsertWithWhereUniqueWithoutSellerInput | Prisma.OrderUpsertWithWhereUniqueWithoutSellerInput[]
  createMany?: Prisma.OrderCreateManySellerInputEnvelope
  set?: Prisma.OrderWhereUniqueInput | Prisma.OrderWhereUniqueInput[]
  disconnect?: Prisma.OrderWhereUniqueInput | Prisma.OrderWhereUniqueInput[]
  delete?: Prisma.OrderWhereUniqueInput | Prisma.OrderWhereUniqueInput[]
  connect?: Prisma.OrderWhereUniqueInput | Prisma.OrderWhereUniqueInput[]
  update?: Prisma.OrderUpdateWithWhereUniqueWithoutSellerInput | Prisma.OrderUpdateWithWhereUniqueWithoutSellerInput[]
  updateMany?: Prisma.OrderUpdateManyWithWhereWithoutSellerInput | Prisma.OrderUpdateManyWithWhereWithoutSellerInput[]
  deleteMany?: Prisma.OrderScalarWhereInput | Prisma.OrderScalarWhereInput[]
}

export type OrderUncheckedUpdateManyWithoutBuyerNestedInput = {
  create?: Prisma.XOR<Prisma.OrderCreateWithoutBuyerInput, Prisma.OrderUncheckedCreateWithoutBuyerInput> | Prisma.OrderCreateWithoutBuyerInput[] | Prisma.OrderUncheckedCreateWithoutBuyerInput[]
  connectOrCreate?: Prisma.OrderCreateOrConnectWithoutBuyerInput | Prisma.OrderCreateOrConnectWithoutBuyerInput[]
  upsert?: Prisma.OrderUpsertWithWhereUniqueWithoutBuyerInput | Prisma.OrderUpsertWithWhereUniqueWithoutBuyerInput[]
  createMany?: Prisma.OrderCreateManyBuyerInputEnvelope
  set?: Prisma.OrderWhereUniqueInput | Prisma.OrderWhereUniqueInput[]
  disconnect?: Prisma.OrderWhereUniqueInput | Prisma.OrderWhereUniqueInput[]
  delete?: Prisma.OrderWhereUniqueInput | Prisma.OrderWhereUniqueInput[]
  connect?: Prisma.OrderWhereUniqueInput | Prisma.OrderWhereUniqueInput[]
  update?: Prisma.OrderUpdateWithWhereUniqueWithoutBuyerInput | Prisma.OrderUpdateWithWhereUniqueWithoutBuyerInput[]
  updateMany?: Prisma.OrderUpdateManyWithWhereWithoutBuyerInput | Prisma.OrderUpdateManyWithWhereWithoutBuyerInput[]
  deleteMany?: Prisma.OrderScalarWhereInput | Prisma.OrderScalarWhereInput[]
}

export type OrderUncheckedUpdateManyWithoutSellerNestedInput = {
  create?: Prisma.XOR<Prisma.OrderCreateWithoutSellerInput, Prisma.OrderUncheckedCreateWithoutSellerInput> | Prisma.OrderCreateWithoutSellerInput[] | Prisma.OrderUncheckedCreateWithoutSellerInput[]
  connectOrCreate?: Prisma.OrderCreateOrConnectWithoutSellerInput | Prisma.OrderCreateOrConnectWithoutSellerInput[]
  upsert?: Prisma.OrderUpsertWithWhereUniqueWithoutSellerInput | Prisma.OrderUpsertWithWhereUniqueWithoutSellerInput[]
  createMany?: Prisma.OrderCreateManySellerInputEnvelope
  set?: Prisma.OrderWhereUniqueInput | Prisma.OrderWhereUniqueInput[]
  disconnect?: Prisma.OrderWhereUniqueInput | Prisma.OrderWhereUniqueInput[]
  delete?: Prisma.OrderWhereUniqueInput | Prisma.OrderWhereUniqueInput[]
  connect?: Prisma.OrderWhereUniqueInput | Prisma.OrderWhereUniqueInput[]
  update?: Prisma.OrderUpdateWithWhereUniqueWithoutSellerInput | Prisma.OrderUpdateWithWhereUniqueWithoutSellerInput[]
  updateMany?: Prisma.OrderUpdateManyWithWhereWithoutSellerInput | Prisma.OrderUpdateManyWithWhereWithoutSellerInput[]
  deleteMany?: Prisma.OrderScalarWhereInput | Prisma.OrderScalarWhereInput[]
}

export type OrderCreateNestedManyWithoutGigInput = {
  create?: Prisma.XOR<Prisma.OrderCreateWithoutGigInput, Prisma.OrderUncheckedCreateWithoutGigInput> | Prisma.OrderCreateWithoutGigInput[] | Prisma.OrderUncheckedCreateWithoutGigInput[]
  connectOrCreate?: Prisma.OrderCreateOrConnectWithoutGigInput | Prisma.OrderCreateOrConnectWithoutGigInput[]
  createMany?: Prisma.OrderCreateManyGigInputEnvelope
  connect?: Prisma.OrderWhereUniqueInput | Prisma.OrderWhereUniqueInput[]
}

export type OrderUncheckedCreateNestedManyWithoutGigInput = {
  create?: Prisma.XOR<Prisma.OrderCreateWithoutGigInput, Prisma.OrderUncheckedCreateWithoutGigInput> | Prisma.OrderCreateWithoutGigInput[] | Prisma.OrderUncheckedCreateWithoutGigInput[]
  connectOrCreate?: Prisma.OrderCreateOrConnectWithoutGigInput | Prisma.OrderCreateOrConnectWithoutGigInput[]
  createMany?: Prisma.OrderCreateManyGigInputEnvelope
  connect?: Prisma.OrderWhereUniqueInput | Prisma.OrderWhereUniqueInput[]
}

export type OrderUpdateManyWithoutGigNestedInput = {
  create?: Prisma.XOR<Prisma.OrderCreateWithoutGigInput, Prisma.OrderUncheckedCreateWithoutGigInput> | Prisma.OrderCreateWithoutGigInput[] | Prisma.OrderUncheckedCreateWithoutGigInput[]
  connectOrCreate?: Prisma.OrderCreateOrConnectWithoutGigInput | Prisma.OrderCreateOrConnectWithoutGigInput[]
  upsert?: Prisma.OrderUpsertWithWhereUniqueWithoutGigInput | Prisma.OrderUpsertWithWhereUniqueWithoutGigInput[]
  createMany?: Prisma.OrderCreateManyGigInputEnvelope
  set?: Prisma.OrderWhereUniqueInput | Prisma.OrderWhereUniqueInput[]
  disconnect?: Prisma.OrderWhereUniqueInput | Prisma.OrderWhereUniqueInput[]
  delete?: Prisma.OrderWhereUniqueInput | Prisma.OrderWhereUniqueInput[]
  connect?: Prisma.OrderWhereUniqueInput | Prisma.OrderWhereUniqueInput[]
  update?: Prisma.OrderUpdateWithWhereUniqueWithoutGigInput | Prisma.OrderUpdateWithWhereUniqueWithoutGigInput[]
  updateMany?: Prisma.OrderUpdateManyWithWhereWithoutGigInput | Prisma.OrderUpdateManyWithWhereWithoutGigInput[]
  deleteMany?: Prisma.OrderScalarWhereInput | Prisma.OrderScalarWhereInput[]
}

export type OrderUncheckedUpdateManyWithoutGigNestedInput = {
  create?: Prisma.XOR<Prisma.OrderCreateWithoutGigInput, Prisma.OrderUncheckedCreateWithoutGigInput> | Prisma.OrderCreateWithoutGigInput[] | Prisma.OrderUncheckedCreateWithoutGigInput[]
  connectOrCreate?: Prisma.OrderCreateOrConnectWithoutGigInput | Prisma.OrderCreateOrConnectWithoutGigInput[]
  upsert?: Prisma.OrderUpsertWithWhereUniqueWithoutGigInput | Prisma.OrderUpsertWithWhereUniqueWithoutGigInput[]
  createMany?: Prisma.OrderCreateManyGigInputEnvelope
  set?: Prisma.OrderWhereUniqueInput | Prisma.OrderWhereUniqueInput[]
  disconnect?: Prisma.OrderWhereUniqueInput | Prisma.OrderWhereUniqueInput[]
  delete?: Prisma.OrderWhereUniqueInput | Prisma.OrderWhereUniqueInput[]
  connect?: Prisma.OrderWhereUniqueInput | Prisma.OrderWhereUniqueInput[]
  update?: Prisma.OrderUpdateWithWhereUniqueWithoutGigInput | Prisma.OrderUpdateWithWhereUniqueWithoutGigInput[]
  updateMany?: Prisma.OrderUpdateManyWithWhereWithoutGigInput | Prisma.OrderUpdateManyWithWhereWithoutGigInput[]
  deleteMany?: Prisma.OrderScalarWhereInput | Prisma.OrderScalarWhereInput[]
}

export type NullableDateTimeFieldUpdateOperationsInput = {
  set?: Date | string | null
}

export type OrderCreateNestedOneWithoutReviewsInput = {
  create?: Prisma.XOR<Prisma.OrderCreateWithoutReviewsInput, Prisma.OrderUncheckedCreateWithoutReviewsInput>
  connectOrCreate?: Prisma.OrderCreateOrConnectWithoutReviewsInput
  connect?: Prisma.OrderWhereUniqueInput
}

export type OrderUpdateOneRequiredWithoutReviewsNestedInput = {
  create?: Prisma.XOR<Prisma.OrderCreateWithoutReviewsInput, Prisma.OrderUncheckedCreateWithoutReviewsInput>
  connectOrCreate?: Prisma.OrderCreateOrConnectWithoutReviewsInput
  upsert?: Prisma.OrderUpsertWithoutReviewsInput
  connect?: Prisma.OrderWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.OrderUpdateToOneWithWhereWithoutReviewsInput, Prisma.OrderUpdateWithoutReviewsInput>, Prisma.OrderUncheckedUpdateWithoutReviewsInput>
}

export type OrderCreateNestedOneWithoutDisputesInput = {
  create?: Prisma.XOR<Prisma.OrderCreateWithoutDisputesInput, Prisma.OrderUncheckedCreateWithoutDisputesInput>
  connectOrCreate?: Prisma.OrderCreateOrConnectWithoutDisputesInput
  connect?: Prisma.OrderWhereUniqueInput
}

export type OrderUpdateOneRequiredWithoutDisputesNestedInput = {
  create?: Prisma.XOR<Prisma.OrderCreateWithoutDisputesInput, Prisma.OrderUncheckedCreateWithoutDisputesInput>
  connectOrCreate?: Prisma.OrderCreateOrConnectWithoutDisputesInput
  upsert?: Prisma.OrderUpsertWithoutDisputesInput
  connect?: Prisma.OrderWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.OrderUpdateToOneWithWhereWithoutDisputesInput, Prisma.OrderUpdateWithoutDisputesInput>, Prisma.OrderUncheckedUpdateWithoutDisputesInput>
}

export type OrderCreateWithoutBuyerInput = {
  id?: string
  status?: string
  amount: runtime.Decimal | runtime.DecimalJsLike | number | string
  delivery_date?: Date | string | null
  created_at?: Date | string
  updated_at?: Date | string
  seller: Prisma.UserCreateNestedOneWithoutOrdersSellerInput
  gig: Prisma.GigCreateNestedOneWithoutOrdersInput
  reviews?: Prisma.ReviewCreateNestedManyWithoutOrderInput
  disputes?: Prisma.DisputeCreateNestedManyWithoutOrderInput
}

export type OrderUncheckedCreateWithoutBuyerInput = {
  id?: string
  seller_id: string
  gig_id: string
  status?: string
  amount: runtime.Decimal | runtime.DecimalJsLike | number | string
  delivery_date?: Date | string | null
  created_at?: Date | string
  updated_at?: Date | string
  reviews?: Prisma.ReviewUncheckedCreateNestedManyWithoutOrderInput
  disputes?: Prisma.DisputeUncheckedCreateNestedManyWithoutOrderInput
}

export type OrderCreateOrConnectWithoutBuyerInput = {
  where: Prisma.OrderWhereUniqueInput
  create: Prisma.XOR<Prisma.OrderCreateWithoutBuyerInput, Prisma.OrderUncheckedCreateWithoutBuyerInput>
}

export type OrderCreateManyBuyerInputEnvelope = {
  data: Prisma.OrderCreateManyBuyerInput | Prisma.OrderCreateManyBuyerInput[]
  skipDuplicates?: boolean
}

export type OrderCreateWithoutSellerInput = {
  id?: string
  status?: string
  amount: runtime.Decimal | runtime.DecimalJsLike | number | string
  delivery_date?: Date | string | null
  created_at?: Date | string
  updated_at?: Date | string
  buyer: Prisma.UserCreateNestedOneWithoutOrdersBuyerInput
  gig: Prisma.GigCreateNestedOneWithoutOrdersInput
  reviews?: Prisma.ReviewCreateNestedManyWithoutOrderInput
  disputes?: Prisma.DisputeCreateNestedManyWithoutOrderInput
}

export type OrderUncheckedCreateWithoutSellerInput = {
  id?: string
  buyer_id: string
  gig_id: string
  status?: string
  amount: runtime.Decimal | runtime.DecimalJsLike | number | string
  delivery_date?: Date | string | null
  created_at?: Date | string
  updated_at?: Date | string
  reviews?: Prisma.ReviewUncheckedCreateNestedManyWithoutOrderInput
  disputes?: Prisma.DisputeUncheckedCreateNestedManyWithoutOrderInput
}

export type OrderCreateOrConnectWithoutSellerInput = {
  where: Prisma.OrderWhereUniqueInput
  create: Prisma.XOR<Prisma.OrderCreateWithoutSellerInput, Prisma.OrderUncheckedCreateWithoutSellerInput>
}

export type OrderCreateManySellerInputEnvelope = {
  data: Prisma.OrderCreateManySellerInput | Prisma.OrderCreateManySellerInput[]
  skipDuplicates?: boolean
}

export type OrderUpsertWithWhereUniqueWithoutBuyerInput = {
  where: Prisma.OrderWhereUniqueInput
  update: Prisma.XOR<Prisma.OrderUpdateWithoutBuyerInput, Prisma.OrderUncheckedUpdateWithoutBuyerInput>
  create: Prisma.XOR<Prisma.OrderCreateWithoutBuyerInput, Prisma.OrderUncheckedCreateWithoutBuyerInput>
}

export type OrderUpdateWithWhereUniqueWithoutBuyerInput = {
  where: Prisma.OrderWhereUniqueInput
  data: Prisma.XOR<Prisma.OrderUpdateWithoutBuyerInput, Prisma.OrderUncheckedUpdateWithoutBuyerInput>
}

export type OrderUpdateManyWithWhereWithoutBuyerInput = {
  where: Prisma.OrderScalarWhereInput
  data: Prisma.XOR<Prisma.OrderUpdateManyMutationInput, Prisma.OrderUncheckedUpdateManyWithoutBuyerInput>
}

export type OrderScalarWhereInput = {
  AND?: Prisma.OrderScalarWhereInput | Prisma.OrderScalarWhereInput[]
  OR?: Prisma.OrderScalarWhereInput[]
  NOT?: Prisma.OrderScalarWhereInput | Prisma.OrderScalarWhereInput[]
  id?: Prisma.StringFilter<"Order"> | string
  buyer_id?: Prisma.StringFilter<"Order"> | string
  seller_id?: Prisma.StringFilter<"Order"> | string
  gig_id?: Prisma.StringFilter<"Order"> | string
  status?: Prisma.StringFilter<"Order"> | string
  amount?: Prisma.DecimalFilter<"Order"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  delivery_date?: Prisma.DateTimeNullableFilter<"Order"> | Date | string | null
  created_at?: Prisma.DateTimeFilter<"Order"> | Date | string
  updated_at?: Prisma.DateTimeFilter<"Order"> | Date | string
}

export type OrderUpsertWithWhereUniqueWithoutSellerInput = {
  where: Prisma.OrderWhereUniqueInput
  update: Prisma.XOR<Prisma.OrderUpdateWithoutSellerInput, Prisma.OrderUncheckedUpdateWithoutSellerInput>
  create: Prisma.XOR<Prisma.OrderCreateWithoutSellerInput, Prisma.OrderUncheckedCreateWithoutSellerInput>
}

export type OrderUpdateWithWhereUniqueWithoutSellerInput = {
  where: Prisma.OrderWhereUniqueInput
  data: Prisma.XOR<Prisma.OrderUpdateWithoutSellerInput, Prisma.OrderUncheckedUpdateWithoutSellerInput>
}

export type OrderUpdateManyWithWhereWithoutSellerInput = {
  where: Prisma.OrderScalarWhereInput
  data: Prisma.XOR<Prisma.OrderUpdateManyMutationInput, Prisma.OrderUncheckedUpdateManyWithoutSellerInput>
}

export type OrderCreateWithoutGigInput = {
  id?: string
  status?: string
  amount: runtime.Decimal | runtime.DecimalJsLike | number | string
  delivery_date?: Date | string | null
  created_at?: Date | string
  updated_at?: Date | string
  buyer: Prisma.UserCreateNestedOneWithoutOrdersBuyerInput
  seller: Prisma.UserCreateNestedOneWithoutOrdersSellerInput
  reviews?: Prisma.ReviewCreateNestedManyWithoutOrderInput
  disputes?: Prisma.DisputeCreateNestedManyWithoutOrderInput
}

export type OrderUncheckedCreateWithoutGigInput = {
  id?: string
  buyer_id: string
  seller_id: string
  status?: string
  amount: runtime.Decimal | runtime.DecimalJsLike | number | string
  delivery_date?: Date | string | null
  created_at?: Date | string
  updated_at?: Date | string
  reviews?: Prisma.ReviewUncheckedCreateNestedManyWithoutOrderInput
  disputes?: Prisma.DisputeUncheckedCreateNestedManyWithoutOrderInput
}

export type OrderCreateOrConnectWithoutGigInput = {
  where: Prisma.OrderWhereUniqueInput
  create: Prisma.XOR<Prisma.OrderCreateWithoutGigInput, Prisma.OrderUncheckedCreateWithoutGigInput>
}

export type OrderCreateManyGigInputEnvelope = {
  data: Prisma.OrderCreateManyGigInput | Prisma.OrderCreateManyGigInput[]
  skipDuplicates?: boolean
}

export type OrderUpsertWithWhereUniqueWithoutGigInput = {
  where: Prisma.OrderWhereUniqueInput
  update: Prisma.XOR<Prisma.OrderUpdateWithoutGigInput, Prisma.OrderUncheckedUpdateWithoutGigInput>
  create: Prisma.XOR<Prisma.OrderCreateWithoutGigInput, Prisma.OrderUncheckedCreateWithoutGigInput>
}

export type OrderUpdateWithWhereUniqueWithoutGigInput = {
  where: Prisma.OrderWhereUniqueInput
  data: Prisma.XOR<Prisma.OrderUpdateWithoutGigInput, Prisma.OrderUncheckedUpdateWithoutGigInput>
}

export type OrderUpdateManyWithWhereWithoutGigInput = {
  where: Prisma.OrderScalarWhereInput
  data: Prisma.XOR<Prisma.OrderUpdateManyMutationInput, Prisma.OrderUncheckedUpdateManyWithoutGigInput>
}

export type OrderCreateWithoutReviewsInput = {
  id?: string
  status?: string
  amount: runtime.Decimal | runtime.DecimalJsLike | number | string
  delivery_date?: Date | string | null
  created_at?: Date | string
  updated_at?: Date | string
  buyer: Prisma.UserCreateNestedOneWithoutOrdersBuyerInput
  seller: Prisma.UserCreateNestedOneWithoutOrdersSellerInput
  gig: Prisma.GigCreateNestedOneWithoutOrdersInput
  disputes?: Prisma.DisputeCreateNestedManyWithoutOrderInput
}

export type OrderUncheckedCreateWithoutReviewsInput = {
  id?: string
  buyer_id: string
  seller_id: string
  gig_id: string
  status?: string
  amount: runtime.Decimal | runtime.DecimalJsLike | number | string
  delivery_date?: Date | string | null
  created_at?: Date | string
  updated_at?: Date | string
  disputes?: Prisma.DisputeUncheckedCreateNestedManyWithoutOrderInput
}

export type OrderCreateOrConnectWithoutReviewsInput = {
  where: Prisma.OrderWhereUniqueInput
  create: Prisma.XOR<Prisma.OrderCreateWithoutReviewsInput, Prisma.OrderUncheckedCreateWithoutReviewsInput>
}

export type OrderUpsertWithoutReviewsInput = {
  update: Prisma.XOR<Prisma.OrderUpdateWithoutReviewsInput, Prisma.OrderUncheckedUpdateWithoutReviewsInput>
  create: Prisma.XOR<Prisma.OrderCreateWithoutReviewsInput, Prisma.OrderUncheckedCreateWithoutReviewsInput>
  where?: Prisma.OrderWhereInput
}

export type OrderUpdateToOneWithWhereWithoutReviewsInput = {
  where?: Prisma.OrderWhereInput
  data: Prisma.XOR<Prisma.OrderUpdateWithoutReviewsInput, Prisma.OrderUncheckedUpdateWithoutReviewsInput>
}

export type OrderUpdateWithoutReviewsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  amount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  delivery_date?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  buyer?: Prisma.UserUpdateOneRequiredWithoutOrdersBuyerNestedInput
  seller?: Prisma.UserUpdateOneRequiredWithoutOrdersSellerNestedInput
  gig?: Prisma.GigUpdateOneRequiredWithoutOrdersNestedInput
  disputes?: Prisma.DisputeUpdateManyWithoutOrderNestedInput
}

export type OrderUncheckedUpdateWithoutReviewsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  buyer_id?: Prisma.StringFieldUpdateOperationsInput | string
  seller_id?: Prisma.StringFieldUpdateOperationsInput | string
  gig_id?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  amount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  delivery_date?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  disputes?: Prisma.DisputeUncheckedUpdateManyWithoutOrderNestedInput
}

export type OrderCreateWithoutDisputesInput = {
  id?: string
  status?: string
  amount: runtime.Decimal | runtime.DecimalJsLike | number | string
  delivery_date?: Date | string | null
  created_at?: Date | string
  updated_at?: Date | string
  buyer: Prisma.UserCreateNestedOneWithoutOrdersBuyerInput
  seller: Prisma.UserCreateNestedOneWithoutOrdersSellerInput
  gig: Prisma.GigCreateNestedOneWithoutOrdersInput
  reviews?: Prisma.ReviewCreateNestedManyWithoutOrderInput
}

export type OrderUncheckedCreateWithoutDisputesInput = {
  id?: string
  buyer_id: string
  seller_id: string
  gig_id: string
  status?: string
  amount: runtime.Decimal | runtime.DecimalJsLike | number | string
  delivery_date?: Date | string | null
  created_at?: Date | string
  updated_at?: Date | string
  reviews?: Prisma.ReviewUncheckedCreateNestedManyWithoutOrderInput
}

export type OrderCreateOrConnectWithoutDisputesInput = {
  where: Prisma.OrderWhereUniqueInput
  create: Prisma.XOR<Prisma.OrderCreateWithoutDisputesInput, Prisma.OrderUncheckedCreateWithoutDisputesInput>
}

export type OrderUpsertWithoutDisputesInput = {
  update: Prisma.XOR<Prisma.OrderUpdateWithoutDisputesInput, Prisma.OrderUncheckedUpdateWithoutDisputesInput>
  create: Prisma.XOR<Prisma.OrderCreateWithoutDisputesInput, Prisma.OrderUncheckedCreateWithoutDisputesInput>
  where?: Prisma.OrderWhereInput
}

export type OrderUpdateToOneWithWhereWithoutDisputesInput = {
  where?: Prisma.OrderWhereInput
  data: Prisma.XOR<Prisma.OrderUpdateWithoutDisputesInput, Prisma.OrderUncheckedUpdateWithoutDisputesInput>
}

export type OrderUpdateWithoutDisputesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  amount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  delivery_date?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  buyer?: Prisma.UserUpdateOneRequiredWithoutOrdersBuyerNestedInput
  seller?: Prisma.UserUpdateOneRequiredWithoutOrdersSellerNestedInput
  gig?: Prisma.GigUpdateOneRequiredWithoutOrdersNestedInput
  reviews?: Prisma.ReviewUpdateManyWithoutOrderNestedInput
}

export type OrderUncheckedUpdateWithoutDisputesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  buyer_id?: Prisma.StringFieldUpdateOperationsInput | string
  seller_id?: Prisma.StringFieldUpdateOperationsInput | string
  gig_id?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  amount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  delivery_date?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  reviews?: Prisma.ReviewUncheckedUpdateManyWithoutOrderNestedInput
}

export type OrderCreateManyBuyerInput = {
  id?: string
  seller_id: string
  gig_id: string
  status?: string
  amount: runtime.Decimal | runtime.DecimalJsLike | number | string
  delivery_date?: Date | string | null
  created_at?: Date | string
  updated_at?: Date | string
}

export type OrderCreateManySellerInput = {
  id?: string
  buyer_id: string
  gig_id: string
  status?: string
  amount: runtime.Decimal | runtime.DecimalJsLike | number | string
  delivery_date?: Date | string | null
  created_at?: Date | string
  updated_at?: Date | string
}

export type OrderUpdateWithoutBuyerInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  amount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  delivery_date?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  seller?: Prisma.UserUpdateOneRequiredWithoutOrdersSellerNestedInput
  gig?: Prisma.GigUpdateOneRequiredWithoutOrdersNestedInput
  reviews?: Prisma.ReviewUpdateManyWithoutOrderNestedInput
  disputes?: Prisma.DisputeUpdateManyWithoutOrderNestedInput
}

export type OrderUncheckedUpdateWithoutBuyerInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  seller_id?: Prisma.StringFieldUpdateOperationsInput | string
  gig_id?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  amount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  delivery_date?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  reviews?: Prisma.ReviewUncheckedUpdateManyWithoutOrderNestedInput
  disputes?: Prisma.DisputeUncheckedUpdateManyWithoutOrderNestedInput
}

export type OrderUncheckedUpdateManyWithoutBuyerInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  seller_id?: Prisma.StringFieldUpdateOperationsInput | string
  gig_id?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  amount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  delivery_date?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type OrderUpdateWithoutSellerInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  amount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  delivery_date?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  buyer?: Prisma.UserUpdateOneRequiredWithoutOrdersBuyerNestedInput
  gig?: Prisma.GigUpdateOneRequiredWithoutOrdersNestedInput
  reviews?: Prisma.ReviewUpdateManyWithoutOrderNestedInput
  disputes?: Prisma.DisputeUpdateManyWithoutOrderNestedInput
}

export type OrderUncheckedUpdateWithoutSellerInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  buyer_id?: Prisma.StringFieldUpdateOperationsInput | string
  gig_id?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  amount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  delivery_date?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  reviews?: Prisma.ReviewUncheckedUpdateManyWithoutOrderNestedInput
  disputes?: Prisma.DisputeUncheckedUpdateManyWithoutOrderNestedInput
}

export type OrderUncheckedUpdateManyWithoutSellerInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  buyer_id?: Prisma.StringFieldUpdateOperationsInput | string
  gig_id?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  amount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  delivery_date?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type OrderCreateManyGigInput = {
  id?: string
  buyer_id: string
  seller_id: string
  status?: string
  amount: runtime.Decimal | runtime.DecimalJsLike | number | string
  delivery_date?: Date | string | null
  created_at?: Date | string
  updated_at?: Date | string
}

export type OrderUpdateWithoutGigInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  amount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  delivery_date?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  buyer?: Prisma.UserUpdateOneRequiredWithoutOrdersBuyerNestedInput
  seller?: Prisma.UserUpdateOneRequiredWithoutOrdersSellerNestedInput
  reviews?: Prisma.ReviewUpdateManyWithoutOrderNestedInput
  disputes?: Prisma.DisputeUpdateManyWithoutOrderNestedInput
}

export type OrderUncheckedUpdateWithoutGigInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  buyer_id?: Prisma.StringFieldUpdateOperationsInput | string
  seller_id?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  amount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  delivery_date?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  reviews?: Prisma.ReviewUncheckedUpdateManyWithoutOrderNestedInput
  disputes?: Prisma.DisputeUncheckedUpdateManyWithoutOrderNestedInput
}

export type OrderUncheckedUpdateManyWithoutGigInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  buyer_id?: Prisma.StringFieldUpdateOperationsInput | string
  seller_id?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  amount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  delivery_date?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}


/**
 * Count Type OrderCountOutputType
 */

export type OrderCountOutputType = {
  reviews: number
  disputes: number
}

export type OrderCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  reviews?: boolean | OrderCountOutputTypeCountReviewsArgs
  disputes?: boolean | OrderCountOutputTypeCountDisputesArgs
}

/**
 * OrderCountOutputType without action
 */
export type OrderCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OrderCountOutputType
   */
  select?: Prisma.OrderCountOutputTypeSelect<ExtArgs> | null
}

/**
 * OrderCountOutputType without action
 */
export type OrderCountOutputTypeCountReviewsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ReviewWhereInput
}

/**
 * OrderCountOutputType without action
 */
export type OrderCountOutputTypeCountDisputesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.DisputeWhereInput
}


export type OrderSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  buyer_id?: boolean
  seller_id?: boolean
  gig_id?: boolean
  status?: boolean
  amount?: boolean
  delivery_date?: boolean
  created_at?: boolean
  updated_at?: boolean
  buyer?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  seller?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  gig?: boolean | Prisma.GigDefaultArgs<ExtArgs>
  reviews?: boolean | Prisma.Order$reviewsArgs<ExtArgs>
  disputes?: boolean | Prisma.Order$disputesArgs<ExtArgs>
  _count?: boolean | Prisma.OrderCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["order"]>

export type OrderSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  buyer_id?: boolean
  seller_id?: boolean
  gig_id?: boolean
  status?: boolean
  amount?: boolean
  delivery_date?: boolean
  created_at?: boolean
  updated_at?: boolean
  buyer?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  seller?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  gig?: boolean | Prisma.GigDefaultArgs<ExtArgs>
}, ExtArgs["result"]["order"]>

export type OrderSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  buyer_id?: boolean
  seller_id?: boolean
  gig_id?: boolean
  status?: boolean
  amount?: boolean
  delivery_date?: boolean
  created_at?: boolean
  updated_at?: boolean
  buyer?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  seller?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  gig?: boolean | Prisma.GigDefaultArgs<ExtArgs>
}, ExtArgs["result"]["order"]>

export type OrderSelectScalar = {
  id?: boolean
  buyer_id?: boolean
  seller_id?: boolean
  gig_id?: boolean
  status?: boolean
  amount?: boolean
  delivery_date?: boolean
  created_at?: boolean
  updated_at?: boolean
}

export type OrderOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "buyer_id" | "seller_id" | "gig_id" | "status" | "amount" | "delivery_date" | "created_at" | "updated_at", ExtArgs["result"]["order"]>
export type OrderInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  buyer?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  seller?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  gig?: boolean | Prisma.GigDefaultArgs<ExtArgs>
  reviews?: boolean | Prisma.Order$reviewsArgs<ExtArgs>
  disputes?: boolean | Prisma.Order$disputesArgs<ExtArgs>
  _count?: boolean | Prisma.OrderCountOutputTypeDefaultArgs<ExtArgs>
}
export type OrderIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  buyer?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  seller?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  gig?: boolean | Prisma.GigDefaultArgs<ExtArgs>
}
export type OrderIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  buyer?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  seller?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  gig?: boolean | Prisma.GigDefaultArgs<ExtArgs>
}

export type $OrderPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Order"
  objects: {
    buyer: Prisma.$UserPayload<ExtArgs>
    seller: Prisma.$UserPayload<ExtArgs>
    gig: Prisma.$GigPayload<ExtArgs>
    reviews: Prisma.$ReviewPayload<ExtArgs>[]
    disputes: Prisma.$DisputePayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    buyer_id: string
    seller_id: string
    gig_id: string
    status: string
    amount: runtime.Decimal
    delivery_date: Date | null
    created_at: Date
    updated_at: Date
  }, ExtArgs["result"]["order"]>
  composites: {}
}

export type OrderGetPayload<S extends boolean | null | undefined | OrderDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$OrderPayload, S>

export type OrderCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<OrderFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: OrderCountAggregateInputType | true
  }

export interface OrderDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Order'], meta: { name: 'Order' } }
  /**
   * Find zero or one Order that matches the filter.
   * @param {OrderFindUniqueArgs} args - Arguments to find a Order
   * @example
   * // Get one Order
   * const order = await prisma.order.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends OrderFindUniqueArgs>(args: Prisma.SelectSubset<T, OrderFindUniqueArgs<ExtArgs>>): Prisma.Prisma__OrderClient<runtime.Types.Result.GetResult<Prisma.$OrderPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Order that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {OrderFindUniqueOrThrowArgs} args - Arguments to find a Order
   * @example
   * // Get one Order
   * const order = await prisma.order.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends OrderFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, OrderFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__OrderClient<runtime.Types.Result.GetResult<Prisma.$OrderPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Order that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {OrderFindFirstArgs} args - Arguments to find a Order
   * @example
   * // Get one Order
   * const order = await prisma.order.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends OrderFindFirstArgs>(args?: Prisma.SelectSubset<T, OrderFindFirstArgs<ExtArgs>>): Prisma.Prisma__OrderClient<runtime.Types.Result.GetResult<Prisma.$OrderPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Order that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {OrderFindFirstOrThrowArgs} args - Arguments to find a Order
   * @example
   * // Get one Order
   * const order = await prisma.order.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends OrderFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, OrderFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__OrderClient<runtime.Types.Result.GetResult<Prisma.$OrderPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Orders that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {OrderFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Orders
   * const orders = await prisma.order.findMany()
   * 
   * // Get first 10 Orders
   * const orders = await prisma.order.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const orderWithIdOnly = await prisma.order.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends OrderFindManyArgs>(args?: Prisma.SelectSubset<T, OrderFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$OrderPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Order.
   * @param {OrderCreateArgs} args - Arguments to create a Order.
   * @example
   * // Create one Order
   * const Order = await prisma.order.create({
   *   data: {
   *     // ... data to create a Order
   *   }
   * })
   * 
   */
  create<T extends OrderCreateArgs>(args: Prisma.SelectSubset<T, OrderCreateArgs<ExtArgs>>): Prisma.Prisma__OrderClient<runtime.Types.Result.GetResult<Prisma.$OrderPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Orders.
   * @param {OrderCreateManyArgs} args - Arguments to create many Orders.
   * @example
   * // Create many Orders
   * const order = await prisma.order.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends OrderCreateManyArgs>(args?: Prisma.SelectSubset<T, OrderCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Orders and returns the data saved in the database.
   * @param {OrderCreateManyAndReturnArgs} args - Arguments to create many Orders.
   * @example
   * // Create many Orders
   * const order = await prisma.order.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Orders and only return the `id`
   * const orderWithIdOnly = await prisma.order.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends OrderCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, OrderCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$OrderPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Order.
   * @param {OrderDeleteArgs} args - Arguments to delete one Order.
   * @example
   * // Delete one Order
   * const Order = await prisma.order.delete({
   *   where: {
   *     // ... filter to delete one Order
   *   }
   * })
   * 
   */
  delete<T extends OrderDeleteArgs>(args: Prisma.SelectSubset<T, OrderDeleteArgs<ExtArgs>>): Prisma.Prisma__OrderClient<runtime.Types.Result.GetResult<Prisma.$OrderPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Order.
   * @param {OrderUpdateArgs} args - Arguments to update one Order.
   * @example
   * // Update one Order
   * const order = await prisma.order.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends OrderUpdateArgs>(args: Prisma.SelectSubset<T, OrderUpdateArgs<ExtArgs>>): Prisma.Prisma__OrderClient<runtime.Types.Result.GetResult<Prisma.$OrderPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Orders.
   * @param {OrderDeleteManyArgs} args - Arguments to filter Orders to delete.
   * @example
   * // Delete a few Orders
   * const { count } = await prisma.order.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends OrderDeleteManyArgs>(args?: Prisma.SelectSubset<T, OrderDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Orders.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {OrderUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Orders
   * const order = await prisma.order.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends OrderUpdateManyArgs>(args: Prisma.SelectSubset<T, OrderUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Orders and returns the data updated in the database.
   * @param {OrderUpdateManyAndReturnArgs} args - Arguments to update many Orders.
   * @example
   * // Update many Orders
   * const order = await prisma.order.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Orders and only return the `id`
   * const orderWithIdOnly = await prisma.order.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends OrderUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, OrderUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$OrderPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Order.
   * @param {OrderUpsertArgs} args - Arguments to update or create a Order.
   * @example
   * // Update or create a Order
   * const order = await prisma.order.upsert({
   *   create: {
   *     // ... data to create a Order
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Order we want to update
   *   }
   * })
   */
  upsert<T extends OrderUpsertArgs>(args: Prisma.SelectSubset<T, OrderUpsertArgs<ExtArgs>>): Prisma.Prisma__OrderClient<runtime.Types.Result.GetResult<Prisma.$OrderPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Orders.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {OrderCountArgs} args - Arguments to filter Orders to count.
   * @example
   * // Count the number of Orders
   * const count = await prisma.order.count({
   *   where: {
   *     // ... the filter for the Orders we want to count
   *   }
   * })
  **/
  count<T extends OrderCountArgs>(
    args?: Prisma.Subset<T, OrderCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], OrderCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Order.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {OrderAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends OrderAggregateArgs>(args: Prisma.Subset<T, OrderAggregateArgs>): Prisma.PrismaPromise<GetOrderAggregateType<T>>

  /**
   * Group by Order.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {OrderGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends OrderGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: OrderGroupByArgs['orderBy'] }
      : { orderBy?: OrderGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, OrderGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetOrderGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Order model
 */
readonly fields: OrderFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Order.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__OrderClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  buyer<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  seller<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  gig<T extends Prisma.GigDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.GigDefaultArgs<ExtArgs>>): Prisma.Prisma__GigClient<runtime.Types.Result.GetResult<Prisma.$GigPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  reviews<T extends Prisma.Order$reviewsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Order$reviewsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ReviewPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  disputes<T extends Prisma.Order$disputesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Order$disputesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$DisputePayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Order model
 */
export interface OrderFieldRefs {
  readonly id: Prisma.FieldRef<"Order", 'String'>
  readonly buyer_id: Prisma.FieldRef<"Order", 'String'>
  readonly seller_id: Prisma.FieldRef<"Order", 'String'>
  readonly gig_id: Prisma.FieldRef<"Order", 'String'>
  readonly status: Prisma.FieldRef<"Order", 'String'>
  readonly amount: Prisma.FieldRef<"Order", 'Decimal'>
  readonly delivery_date: Prisma.FieldRef<"Order", 'DateTime'>
  readonly created_at: Prisma.FieldRef<"Order", 'DateTime'>
  readonly updated_at: Prisma.FieldRef<"Order", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Order findUnique
 */
export type OrderFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Order
   */
  select?: Prisma.OrderSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Order
   */
  omit?: Prisma.OrderOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OrderInclude<ExtArgs> | null
  /**
   * Filter, which Order to fetch.
   */
  where: Prisma.OrderWhereUniqueInput
}

/**
 * Order findUniqueOrThrow
 */
export type OrderFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Order
   */
  select?: Prisma.OrderSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Order
   */
  omit?: Prisma.OrderOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OrderInclude<ExtArgs> | null
  /**
   * Filter, which Order to fetch.
   */
  where: Prisma.OrderWhereUniqueInput
}

/**
 * Order findFirst
 */
export type OrderFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Order
   */
  select?: Prisma.OrderSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Order
   */
  omit?: Prisma.OrderOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OrderInclude<ExtArgs> | null
  /**
   * Filter, which Order to fetch.
   */
  where?: Prisma.OrderWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Orders to fetch.
   */
  orderBy?: Prisma.OrderOrderByWithRelationInput | Prisma.OrderOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Orders.
   */
  cursor?: Prisma.OrderWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Orders from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Orders.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Orders.
   */
  distinct?: Prisma.OrderScalarFieldEnum | Prisma.OrderScalarFieldEnum[]
}

/**
 * Order findFirstOrThrow
 */
export type OrderFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Order
   */
  select?: Prisma.OrderSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Order
   */
  omit?: Prisma.OrderOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OrderInclude<ExtArgs> | null
  /**
   * Filter, which Order to fetch.
   */
  where?: Prisma.OrderWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Orders to fetch.
   */
  orderBy?: Prisma.OrderOrderByWithRelationInput | Prisma.OrderOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Orders.
   */
  cursor?: Prisma.OrderWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Orders from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Orders.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Orders.
   */
  distinct?: Prisma.OrderScalarFieldEnum | Prisma.OrderScalarFieldEnum[]
}

/**
 * Order findMany
 */
export type OrderFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Order
   */
  select?: Prisma.OrderSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Order
   */
  omit?: Prisma.OrderOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OrderInclude<ExtArgs> | null
  /**
   * Filter, which Orders to fetch.
   */
  where?: Prisma.OrderWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Orders to fetch.
   */
  orderBy?: Prisma.OrderOrderByWithRelationInput | Prisma.OrderOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Orders.
   */
  cursor?: Prisma.OrderWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Orders from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Orders.
   */
  skip?: number
  distinct?: Prisma.OrderScalarFieldEnum | Prisma.OrderScalarFieldEnum[]
}

/**
 * Order create
 */
export type OrderCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Order
   */
  select?: Prisma.OrderSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Order
   */
  omit?: Prisma.OrderOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OrderInclude<ExtArgs> | null
  /**
   * The data needed to create a Order.
   */
  data: Prisma.XOR<Prisma.OrderCreateInput, Prisma.OrderUncheckedCreateInput>
}

/**
 * Order createMany
 */
export type OrderCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Orders.
   */
  data: Prisma.OrderCreateManyInput | Prisma.OrderCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Order createManyAndReturn
 */
export type OrderCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Order
   */
  select?: Prisma.OrderSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Order
   */
  omit?: Prisma.OrderOmit<ExtArgs> | null
  /**
   * The data used to create many Orders.
   */
  data: Prisma.OrderCreateManyInput | Prisma.OrderCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OrderIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Order update
 */
export type OrderUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Order
   */
  select?: Prisma.OrderSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Order
   */
  omit?: Prisma.OrderOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OrderInclude<ExtArgs> | null
  /**
   * The data needed to update a Order.
   */
  data: Prisma.XOR<Prisma.OrderUpdateInput, Prisma.OrderUncheckedUpdateInput>
  /**
   * Choose, which Order to update.
   */
  where: Prisma.OrderWhereUniqueInput
}

/**
 * Order updateMany
 */
export type OrderUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Orders.
   */
  data: Prisma.XOR<Prisma.OrderUpdateManyMutationInput, Prisma.OrderUncheckedUpdateManyInput>
  /**
   * Filter which Orders to update
   */
  where?: Prisma.OrderWhereInput
  /**
   * Limit how many Orders to update.
   */
  limit?: number
}

/**
 * Order updateManyAndReturn
 */
export type OrderUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Order
   */
  select?: Prisma.OrderSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Order
   */
  omit?: Prisma.OrderOmit<ExtArgs> | null
  /**
   * The data used to update Orders.
   */
  data: Prisma.XOR<Prisma.OrderUpdateManyMutationInput, Prisma.OrderUncheckedUpdateManyInput>
  /**
   * Filter which Orders to update
   */
  where?: Prisma.OrderWhereInput
  /**
   * Limit how many Orders to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OrderIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Order upsert
 */
export type OrderUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Order
   */
  select?: Prisma.OrderSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Order
   */
  omit?: Prisma.OrderOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OrderInclude<ExtArgs> | null
  /**
   * The filter to search for the Order to update in case it exists.
   */
  where: Prisma.OrderWhereUniqueInput
  /**
   * In case the Order found by the `where` argument doesn't exist, create a new Order with this data.
   */
  create: Prisma.XOR<Prisma.OrderCreateInput, Prisma.OrderUncheckedCreateInput>
  /**
   * In case the Order was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.OrderUpdateInput, Prisma.OrderUncheckedUpdateInput>
}

/**
 * Order delete
 */
export type OrderDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Order
   */
  select?: Prisma.OrderSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Order
   */
  omit?: Prisma.OrderOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OrderInclude<ExtArgs> | null
  /**
   * Filter which Order to delete.
   */
  where: Prisma.OrderWhereUniqueInput
}

/**
 * Order deleteMany
 */
export type OrderDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Orders to delete
   */
  where?: Prisma.OrderWhereInput
  /**
   * Limit how many Orders to delete.
   */
  limit?: number
}

/**
 * Order.reviews
 */
export type Order$reviewsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Review
   */
  select?: Prisma.ReviewSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Review
   */
  omit?: Prisma.ReviewOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ReviewInclude<ExtArgs> | null
  where?: Prisma.ReviewWhereInput
  orderBy?: Prisma.ReviewOrderByWithRelationInput | Prisma.ReviewOrderByWithRelationInput[]
  cursor?: Prisma.ReviewWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.ReviewScalarFieldEnum | Prisma.ReviewScalarFieldEnum[]
}

/**
 * Order.disputes
 */
export type Order$disputesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Dispute
   */
  select?: Prisma.DisputeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Dispute
   */
  omit?: Prisma.DisputeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DisputeInclude<ExtArgs> | null
  where?: Prisma.DisputeWhereInput
  orderBy?: Prisma.DisputeOrderByWithRelationInput | Prisma.DisputeOrderByWithRelationInput[]
  cursor?: Prisma.DisputeWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.DisputeScalarFieldEnum | Prisma.DisputeScalarFieldEnum[]
}

/**
 * Order without action
 */
export type OrderDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Order
   */
  select?: Prisma.OrderSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Order
   */
  omit?: Prisma.OrderOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OrderInclude<ExtArgs> | null
}
